"""Generate the native and web catalogs from the reviewed TSV. Run after editing it."""
import json
from pathlib import Path
root = Path(__file__).resolve().parents[1]
entries = {}
for line in (root/'ui/translations.tsv').read_text(encoding='utf-8').splitlines():
    if line:
        key, value = line.split('\t', 1)
        entries[key] = value
items = sorted(entries.items(), key=lambda pair: len(pair[0]), reverse=True)
quote = lambda s: 'L' + json.dumps(s, ensure_ascii=False)
header = '''// Generated by tools/generate_translations.py; edit ui/translations.tsv.
#pragma once
#include <string>
#include <utility>
namespace EaiLanguage {
inline bool english = false;
inline std::wstring Translate(const std::wstring& text) {
 if(!english) return text;
 static const std::pair<std::wstring,std::wstring> catalog[]{
'''
header += ''.join('  {'+quote(k)+','+quote(v)+'},\n' for k,v in items)
header += ''' };
 std::wstring result;
 for(size_t pos=0;pos<text.size();){bool matched=false;
  for(const auto& [source,target]:catalog) if(text.compare(pos,source.size(),source)==0){result+=target;pos+=source.size();matched=true;break;}
  if(!matched)result+=text[pos++];
 }
 return result;
}
}
'''
(root/'src/language_catalog.h').write_text(header,encoding='utf-8')
js = '// Generated by tools/generate_translations.py; edit ui/translations.tsv.\n'
js += 'const eaiTranslations = '+json.dumps(items,ensure_ascii=False)+';\n'
js += '''function translateEai(text, english) {
 if(!english)return text;
 let result='';
 for(let pos=0;pos<text.length;){let found=false;
  for(const [source,target] of eaiTranslations)if(text.startsWith(source,pos)){result+=target;pos+=source.length;found=true;break;}
  if(!found)result+=text[pos++];
 }
 return result;
}
if(typeof module!=='undefined')module.exports={translateEai,eaiTranslations};
'''
(root/'ui/language-catalog.js').write_text(js,encoding='utf-8')
