#include "efmi_bridge.h"
#include <iostream>
#include <chrono>
#include <cstring>
int main(int argc,char** argv){using namespace EfmiBridge;int fail=0;auto check=[&](bool ok,const char* name){if(!ok){++fail;std::cerr<<name<<"\n";}};
 auto temp=std::filesystem::temp_directory_path()/("bem-efmi-tests-"+std::to_string(std::chrono::steady_clock::now().time_since_epoch().count()));auto mods=temp/"Mods";auto folder=mods/std::filesystem::path(u8"測試 mod");std::filesystem::create_directories(folder);
 auto file=folder/std::filesystem::path(u8"配件.ini");std::string source="[Constants]\nglobal persist $shape = 0.0\nglobal persist $show = 1\n[Present]\nif $shape < 0\n$shape = 0\nelif $shape > 1\n$shape = 1\nendif\n$shape = $shape + 0.01\n[TextureOverrideMesh]\nvb0 = ResourceVertices\nif $show == 1\n; [mesh:dragon-horn] [vertex_count:42]\ndrawindexed = 6,0,0\nendif\n";
 {std::ofstream out(temp/"d3dx.ini");out<<"[Include]\ninclude_recursive = Mods\n[Hunting]\nreload_config = no_modifiers VK_F10\n";}{std::ofstream out(file,std::ios::binary);out<<source;}
 auto scan=Discover(folder);check(scan.mods.size()==1,"scans INI");check(scan.reloadKey=="no_modifiers VK_F10","reads reload key");check(scan.mods[0].meshes.size()==1&&scan.mods[0].meshes[0].condition=="$show == 1","mesh name and draw condition");check(!scan.mods[0].controls[0].integer,"continuous shape is not reduced to binary");
 check(scan.mods[0].space.find("Mods\\")==0,"Unicode filename namespace resolved relative to EFMI root");auto& c=scan.mods[0].controls[0];c.value=.5f;c.dirty=true;auto text=Generate(scan);check(text.find("\\shape = 0.5")!=text.npos,"writes qualified shape override");check(text.find("\\show = ")==text.npos,"only edited controls are overridden");check(ReadFile(file)==source,"original mod is unchanged");
 auto output=OutputPath(scan);check(std::filesystem::equivalent(output.parent_path(),folder),"output confined to selected mod");auto aliasScan=Discover(folder/".");check(std::filesystem::equivalent(OutputPath(aliasScan).parent_path(),folder),"normalized selected folder preserves output location");{std::ofstream out(output);out<<"foreign file";}bool refused=false;try{Owned(output);}catch(...){refused=true;}check(refused,"unowned file is not overwritten");std::filesystem::remove(output);c.value=2;refused=false;try{Generate(scan);}catch(...){refused=true;}check(refused,"range validation");c.value=.5;c.binding="$bad\n[Present]";refused=false;try{Generate(scan);}catch(...){refused=true;}check(refused,"INI injection rejected");
 auto component=Parse(file,"[CommandList_Draw_Component9]\nib = ref ResourceIB\nvb0 = ref ResourceVB\n; Draw Component 9 base\ndrawindexedinstanced = 6, INSTANCE_COUNT, 0, 0, FIRST_INSTANCE\nif $shoes == 1\n; Draw Component 9 shoes\ndrawindexedinstanced = 3, INSTANCE_COUNT, 6, 0, FIRST_INSTANCE\nendif\n",temp);
 check(component.meshes.size()==2,"Draw Component named submeshes detected");check(component.meshes[1].name=="Component 9 / shoes"&&component.meshes[1].condition=="$shoes == 1","component name and condition preserved");check(component.meshes[1].resource=="ResourceVB"&&component.meshes[1].indexResource=="ResourceIB"&&component.meshes[1].start==6&&component.meshes[1].count==3,"ref resources and instanced draw range decoded");
 if(argc>1){auto real=Discover(std::filesystem::path(std::u8string(argv[1],argv[1]+std::strlen(argv[1]))));size_t meshes=0,controls=0;bool shape=false,continuousShape=false;for(auto& m:real.mods){meshes+=m.meshes.size();if(m.name=="Endmin D-Out!"){check(m.meshes.size()>=11,"real Endmin components discovered");check(std::any_of(m.meshes.begin(),m.meshes.end(),[](auto& mesh){return mesh.name=="Component 9 / shoes"&&mesh.count==18084&&mesh.start==407265&&mesh.resource=="Resource_Component9_VB0";}),"real Endmin shoes range and resource resolved");}controls+=m.controls.size();for(auto& p:m.controls)if(p.binding=="$Freq_shape"){shape=true;continuousShape=!p.integer;p.value=.5;p.dirty=true;}}check(shape&&continuousShape,"real wings detected as continuous shape");auto generated=Generate(real);check(generated.find("\\Freq_shape = 0.5")!=generated.npos,"real wing bridge generated without modifying mod");std::cout<<"Read-only real scan: "<<real.mods.size()<<" INIs, "<<meshes<<" meshes, "<<controls<<" controls\n";}
 // Remove only the files created by this isolated test.
 std::filesystem::remove(file);std::filesystem::remove(temp/"d3dx.ini");std::filesystem::remove(folder);std::filesystem::remove(mods);std::filesystem::remove(temp);return fail?1:0;}
