#pragma once
#include "efmi_bridge.h"
#include <cstring>
#include <limits>
namespace ExternalMesh {
using Bytes=std::vector<unsigned char>;using Vec=std::array<float,3>;
inline std::filesystem::path ResourceFile(const EfmiBridge::Mod& mod,const EfmiBridge::Resource& r){if(r.file.empty())throw std::runtime_error("Resource has no source file");auto text=r.file;std::replace(text.begin(),text.end(),'\\','/');auto path=std::filesystem::weakly_canonical(mod.file.parent_path()/std::filesystem::path(std::u8string(text.begin(),text.end())));auto relative=path.lexically_relative(std::filesystem::weakly_canonical(mod.file.parent_path()));if(relative.empty()||EfmiBridge::Utf8(relative).starts_with(".."))throw std::runtime_error("Resource outside mod folder is unsupported");return path;}
inline Bytes Read(const std::filesystem::path& path){auto size=std::filesystem::file_size(path);if(!size||size>268435456)throw std::runtime_error("Buffer empty or above 256 MB");Bytes bytes(size);std::ifstream in(path,std::ios::binary);if(!in.read(reinterpret_cast<char*>(bytes.data()),size))throw std::runtime_error("Buffer read failed");return bytes;}
template<class T> inline T Get(const Bytes& bytes,size_t offset){if(offset>bytes.size()||sizeof(T)>bytes.size()-offset)throw std::runtime_error("Buffer offset is out of range");T value;std::memcpy(&value,bytes.data()+offset,sizeof(T));return value;}
template<class T> inline void Put(Bytes& bytes,size_t offset,T value){if(offset>bytes.size()||sizeof(T)>bytes.size()-offset)throw std::runtime_error("Buffer write is out of range");std::memcpy(bytes.data()+offset,&value,sizeof(T));}
inline Vec Vertex(const Bytes& bytes,size_t offset){Vec v{Get<float>(bytes,offset),Get<float>(bytes,offset+4),Get<float>(bytes,offset+8)};for(auto x:v)if(!std::isfinite(x)||std::abs(x)>10000)throw std::runtime_error("Position layout is not supported");return v;}
inline std::set<size_t> Indices(const EfmiBridge::Mod& mod,const EfmiBridge::Mesh& m,size_t vertices){auto found=mod.resources.find(m.indexResource);if(found==mod.resources.end()||!m.count||m.count%3)throw std::runtime_error("Missing literal indexed draw range");auto format=EfmiBridge::Lower(found->second.format);size_t width=format.find("r32_uint")!=format.npos?4:format.find("r16_uint")!=format.npos?2:0;if(!width)throw std::runtime_error("Index format unsupported");auto data=Read(ResourceFile(mod,found->second));if(data.size()%width||m.start>data.size()/width||m.count>data.size()/width-m.start)throw std::runtime_error("Index draw range exceeds source buffer");std::set<size_t> result;for(size_t i=m.start;i<m.start+m.count;++i){int64_t index=(width==4?Get<uint32_t>(data,i*width):Get<uint16_t>(data,i*width))+m.base;if(index<0||uint64_t(index)>=vertices)throw std::runtime_error("Index points outside position buffer");result.insert(size_t(index));}return result;}
inline const EfmiBridge::Resource& PositionResource(const EfmiBridge::Mod& mod,const EfmiBridge::Mesh& m){auto r=mod.resources.find(m.resource);if(r==mod.resources.end()||(r->second.stride!=12&&r->second.stride!=16)||r->second.file.empty())throw std::runtime_error("Only file-backed float3 positions with stride 12 or 16 are supported");return r->second;}
inline void Probe(EfmiBridge::Mod& mod,EfmiBridge::Mesh& m){try{auto& r=PositionResource(mod,m);auto data=Read(ResourceFile(mod,r));if(data.size()%r.stride)throw std::runtime_error("Position buffer stride mismatch");auto indices=Indices(mod,m,data.size()/r.stride);Vec low{1e10f,1e10f,1e10f},high{-1e10f,-1e10f,-1e10f};for(auto index:indices){auto v=Vertex(data,index*r.stride);for(int k=0;k<3;++k){low[k]=std::min(low[k],v[k]);high[k]=std::max(high[k],v[k]);}}for(int k=0;k<3;++k)m.values[9+k]=(low[k]+high[k])*50.f;m.supported=true;m.reason="可調整；支點預設網格包圍盒中心，XYZ 為模型局部座標";}catch(const std::exception& e){m.supported=false;m.reason=e.what();}}
inline bool Valid(const std::array<float,12>& v){for(int i=0;i<12;++i){float lo=i<3?-200:i<6?-180:i<9?.1f:-10000,hi=i<3?200:i<6?180:i<9?3.f:10000;if(!std::isfinite(v[i])||v[i]<lo||v[i]>hi)return false;}return true;}
inline Vec Linear(Vec p,const std::array<float,12>& v){constexpr float rad=3.14159265358979323846f/180.f;for(int k=0;k<3;++k)p[k]*=v[6+k];for(int axis=0;axis<3;++axis){int a=(axis+1)%3,b=(axis+2)%3;float c=std::cos(v[3+axis]*rad),s=std::sin(v[3+axis]*rad),pa=p[a],pb=p[b];p[a]=c*pa-s*pb;p[b]=s*pa+c*pb;}return p;}
inline Vec Transform(Vec p,const std::array<float,12>& v){for(int k=0;k<3;++k)p[k]-=v[9+k]*.01f;p=Linear(p,v);for(int k=0;k<3;++k)p[k]+=(v[9+k]+v[k])*.01f;return p;}
struct Buffer {std::filesystem::path source;Bytes bytes;int stride;std::vector<std::pair<std::string,std::string>> aliases;std::map<size_t,std::array<float,12>> changed;};
inline constexpr char Marker[]="; BEM EXTERNAL MESH v1";
inline std::vector<Buffer> Build(const EfmiBridge::Scan& scan){std::map<std::string,Buffer> buffers;
 for(auto& mod:scan.mods)for(auto& mesh:mod.meshes)if(mesh.dirty){if(!mesh.supported||!Valid(mesh.values))throw std::runtime_error("Invalid mesh transform");auto fresh=EfmiBridge::Parse(mod.file,EfmiBridge::ReadFile(mod.file),scan.efmiRoot);auto match=std::find_if(fresh.meshes.begin(),fresh.meshes.end(),[&](auto& m){return m.name==mesh.name;});if(match==fresh.meshes.end()||match->resource!=mesh.resource||match->start!=mesh.start||match->count!=mesh.count||match->base!=mesh.base)throw std::runtime_error("Mesh draw changed; rescan first");auto& r=PositionResource(fresh,*match);auto path=ResourceFile(fresh,r);auto key=EfmiBridge::Utf8(path);if(!buffers.contains(key))buffers[key]={path,Read(path),r.stride};auto& buffer=buffers.at(key);auto indices=Indices(fresh,*match,buffer.bytes.size()/r.stride);
 for(auto index:indices){auto prior=buffer.changed.find(index);if(prior!=buffer.changed.end()){if(prior->second!=mesh.values)throw std::runtime_error("Shared vertices have conflicting mesh transforms");continue;}auto v=Transform(Vertex(buffer.bytes,index*r.stride),mesh.values);for(int k=0;k<3;++k)Put<float>(buffer.bytes,index*r.stride+k*4,v[k]);buffer.changed[index]=mesh.values;}
 // Preserve aliases used by shape-key reset/copy and normal draw paths.
 for(auto& [name,alias]:fresh.resources)if(!alias.file.empty()&&alias.stride==r.stride&&ResourceFile(fresh,alias)==path){auto pair=std::make_pair(fresh.space,name);if(std::find(buffer.aliases.begin(),buffer.aliases.end(),pair)==buffer.aliases.end())buffer.aliases.push_back(pair);}
 }
 // Refuse edits that would deform a distinct unselected submesh sharing vertices.
 for(auto& mod:scan.mods)for(auto& mesh:mod.meshes)if(!mesh.dirty&&mesh.supported){auto& r=PositionResource(mod,mesh);auto key=EfmiBridge::Utf8(ResourceFile(mod,r));auto found=buffers.find(key);if(found==buffers.end())continue;auto ids=Indices(mod,mesh,found->second.bytes.size()/r.stride);for(auto id:ids)if(found->second.changed.contains(id))throw std::runtime_error("Selected mesh shares vertices with an unselected mesh; edit both together");}
 // Packed position-only shape deltas must follow the same linear transform.
 std::vector<Buffer> deltas;for(auto& [key,b]:buffers){auto mapFile=b.source.parent_path()/(b.source.stem().wstring()+L"_merged_map.buf"),deltaFile=b.source.parent_path()/(b.source.stem().wstring()+L"_merged_packed_pos_delta.buf");bool mapExists=std::filesystem::exists(mapFile),deltaExists=std::filesystem::exists(deltaFile);if(mapExists!=deltaExists)throw std::runtime_error("Incomplete shape delta data");if(!mapExists)continue;auto map=Read(mapFile),data=Read(deltaFile);size_t vertices=b.bytes.size()/b.stride;if(map.size()!=vertices*4||data.size()%12)throw std::runtime_error("Only one-slot packed position shape maps are supported");std::map<int32_t,std::array<float,12>> selected;
 for(auto& [vertex,v]:b.changed){int32_t index=Get<int32_t>(map,vertex*4);if(index<0)continue;if(size_t(index)>=data.size()/12)throw std::runtime_error("Shape map index out of range");if(selected.contains(index)&&selected[index]!=v)throw std::runtime_error("Shared shape deltas have conflicting transforms");selected[index]=v;}
 for(size_t vertex=0;vertex<vertices;++vertex)if(!b.changed.contains(vertex)){auto index=Get<int32_t>(map,vertex*4);if(selected.contains(index))throw std::runtime_error("Shape delta shared with unselected vertices");}
 for(auto& [index,v]:selected){auto value=Linear(Vertex(data,size_t(index)*12),v);for(int k=0;k<3;++k)Put<float>(data,size_t(index)*12+k*4,value[k]);}
 Buffer delta{deltaFile,std::move(data),12};for(auto& mod:scan.mods)for(auto& [name,r]:mod.resources)if(!r.file.empty()&&r.stride==12&&ResourceFile(mod,r)==deltaFile)delta.aliases.push_back({mod.space,name});if(delta.aliases.empty())throw std::runtime_error("Cannot bind transformed shape delta buffer");deltas.push_back(std::move(delta));
 }
 std::vector<Buffer> result;for(auto& [key,b]:buffers)result.push_back(std::move(b));for(auto& b:deltas)result.push_back(std::move(b));return result;}
inline std::string Ini(const std::vector<Buffer>& buffers,const std::string& revision){std::ostringstream out;out<<Marker<<"\nnamespace = BEMExternalMesh\n\n[Constants]\n";for(size_t i=0;i<buffers.size();++i)for(auto& [space,name]:buffers[i].aliases){if(!name.starts_with("Resource")||space.find_first_of("\r\n[];=$")!=space.npos)throw std::runtime_error("Invalid mesh resource namespace");out<<"post Resource\\"<<space<<"\\"<<name.substr(8)<<" = ref ResourceBEMBuffer"<<i<<"\n";}for(size_t i=0;i<buffers.size();++i)out<<"\n[ResourceBEMBuffer"<<i<<"]\ntype = Buffer\nstride = "<<buffers[i].stride<<"\nfilename = BEM.GeneratedMeshes/"<<revision<<"/buffer"<<i<<".buf\n";return out.str();}
}
