#include "external_mesh.h"
#include <iostream>
#include <chrono>
#include <cstring>
int main(int argc,char** argv){using namespace ExternalMesh;int fail=0;auto check=[&](bool ok,const char* name){if(!ok){++fail;std::cerr<<name<<"\n";}};
 auto dir=std::filesystem::temp_directory_path()/("bem-mesh-tests-"+std::to_string(std::chrono::steady_clock::now().time_since_epoch().count()));std::filesystem::create_directories(dir);auto file=dir/"mod.ini";std::string source="namespace = TestMod\n[TextureOverrideTest]\nib = ResourceIndex\nvb0 = ResourcePosition\n; [mesh:horn]\ndrawindexed = 3,0,0\n[ResourceIndex]\nformat = R32_UINT\nfilename = Index.buf\n[ResourcePosition]\nstride = 16\nfilename = Position.buf\n[ResourcePosition_0]\nstride = 16\nfilename = Position.buf\n[ResourceDelta]\nstride = 12\nfilename = Position_merged_packed_pos_delta.buf\n";
 auto write=[&](const std::filesystem::path& path,const Bytes& bytes){std::ofstream out(path,std::ios::binary);out.write(reinterpret_cast<const char*>(bytes.data()),bytes.size());};
 Bytes positions(64),indices(12),mapping(16),delta(36);for(int i=0;i<4;++i){Put<float>(positions,i*16,float(i==1));Put<float>(positions,i*16+4,float(i==2));Put<uint32_t>(positions,i*16+12,0xAB123456);Put<int32_t>(mapping,i*4,i<3?i:-1);}for(int i=0;i<3;++i){Put<uint32_t>(indices,i*4,i);Put<float>(delta,i*12,1);}
 write(dir/"Position.buf",positions);write(dir/"Index.buf",indices);write(dir/"Position_merged_map.buf",mapping);write(dir/"Position_merged_packed_pos_delta.buf",delta);{std::ofstream out(file,std::ios::binary);out<<source;}
 auto mod=EfmiBridge::Parse(file,source,dir);check(mod.meshes.size()==1&&mod.meshes[0].count==3,"literal mesh draw scanned");Probe(mod,mod.meshes[0]);check(mod.meshes[0].supported,"known vertex format probed");mod.meshes[0].values={10,0,0,0,0,90,2,2,2,0,0,0};mod.meshes[0].dirty=true;EfmiBridge::Scan scan;scan.mods={mod};auto buffers=Build(scan);check(buffers.size()==2,"position and shape buffers generated");auto p=Vertex(buffers[0].bytes,16);check(std::abs(p[0]-.1f)<.0001f&&std::abs(p[1]-2)<.0001f,"scale rotate translate around pivot");check(Get<uint32_t>(buffers[0].bytes,28)==0xAB123456,"packed attribute bytes preserved");check(std::equal(positions.begin()+48,positions.end(),buffers[0].bytes.begin()+48),"unselected vertex unchanged");auto d=Vertex(buffers[1].bytes,0);check(std::abs(d[0])<.0001f&&std::abs(d[1]-2)<.0001f,"shape delta transformed without translation");check(Read(dir/"Position.buf")==positions,"source position buffer unchanged");auto ini=Ini(buffers,"revision");check(ini.find("post Resource\\TestMod\\Position = ref ResourceBEMBuffer0")!=ini.npos&&ini.find("post Resource\\TestMod\\Position_0")!=ini.npos,"namespace aliases cover dynamic shape reset source");check(ini.find("filename = BEM.GeneratedMeshes/revision/buffer0.buf")!=ini.npos,"generated buffer isolated");
 scan.mods[0].meshes.push_back(scan.mods[0].meshes[0]);scan.mods[0].meshes.back().name="unselected-shared";scan.mods[0].meshes.back().dirty=false;bool refused=false;try{Build(scan);}catch(...){refused=true;}check(refused,"unselected shared mesh refused");
 if(argc>1){auto real=EfmiBridge::Discover(std::filesystem::path(std::u8string(argv[1],argv[1]+std::strlen(argv[1]))));int supported=0,wings=0;for(auto& m:real.mods)for(auto& mesh:m.meshes){Probe(m,mesh);if(mesh.supported)++supported;if(EfmiBridge::MeshLabel(mesh.name)=="魅魔翅膀.001"){check(mesh.supported,"real wing mesh supported");if(mesh.supported){mesh.values[6]=mesh.values[7]=mesh.values[8]=1.1f;mesh.dirty=true;++wings;}}}try{auto result=Build(real);check(wings==2&&result.size()>=4,"real LOD wings and packed deltas generated");std::cout<<"Read-only real mesh test: "<<supported<<" supported meshes; "<<wings<<" wing LOD meshes; "<<result.size()<<" generated buffers (not written)\n";}catch(const std::exception& e){++fail;std::cerr<<"Real mesh build: "<<e.what()<<"\n";}}
 for(auto& name:{"mod.ini","Position.buf","Index.buf","Position_merged_map.buf","Position_merged_packed_pos_delta.buf"})std::filesystem::remove(dir/name);std::filesystem::remove(dir);return fail?1:0;}
