// Exercise the real native module logic with managed invocations simulated.
// This does not validate game ABI, Unity thread ordering or visual behavior.
#include "diagnostic.cpp"
#include <cstdio>
#include <cstring>
#include <map>
namespace Fake {
struct Object {std::string name;Object* parent=nullptr;std::vector<Object*> children;PoseMath::Quaternion rotation{};PoseMath::Vector3 position{},scale{1,1,1};bool hierarchical=false;};
Object entity{},go{"chr_0003_endminf_postmodel(Clone)#test"},root{"root"},neck{"Bip001_Neck"},head{"Bip001_Head"},body{"body"},weapon{"weapon"},weaponRoot{"weapon-root"},array{"array"};
Object targetEntity{},targetGo{"chr_0004_pelica_postmodel(Clone)#test"},targetRoot{"target-root"},targetNeck{"Bip001_Neck"},targetHead{"Bip001_Head"},manager{};
Object targetBody{"target-body"},targetArray{"target-array"};
std::map<const void*,uint64_t> owners;const void* busyRoot=nullptr;bool failPartner=false;uint64_t sequence=100;
bool failTargetPlacement=false;
const void* failedArm=nullptr;
bool controlledMoving=false,partnerMoving=false,partnerAirborne=false,movementUnavailable=false;
bool targetPresent=true;
BE_Result replyResult=BE_Result_Ok;std::string replyBody;
BE_Result BE_CALL Reply(void*,const char*,BE_Result result,const char* json){replyResult=result;replyBody=json;return BE_Result_Ok;}
bool leaseBusy=false;uint64_t token=0;int pins=0,writes=0,failures=0;bool failWrite=false;
alignas(16) unsigned char boxed[32]{};
bool Arm(Object* o){return o&&(o->name.find("UpArmTwist")!=std::string::npos||o->name=="Bip001_L_UpperArm"||o->name=="Bip001_L_Forearm"||o->name=="Bip001_L_Hand"||o->name.starts_with("Bip001_L_Finger")||o->name=="Bip001_R_UpperArm"||o->name=="Bip001_R_Forearm"||o->name=="Bip001_R_Hand"||o->name.starts_with("Bip001_R_Finger"));}
PoseMath::Quaternion World(Object* o){return (Arm(o)||o->hierarchical)&&o->parent?PoseMath::Multiply(World(o->parent),o->rotation):o->rotation;}
PoseMath::Vector3 WorldPosition(Object* o){return (Arm(o)||o->hierarchical)&&o->parent?Handshake::Add(WorldPosition(o->parent),PoseMath::Rotate(World(o->parent),o->position)):o->position;}
template<class T> void* Box(T value){std::memcpy(boxed,&value,sizeof(value));return boxed;}
void* BE_CALL Invoke(void*,const void* method,void* self,void** args,void** exception){
 auto key=static_cast<Key>(reinterpret_cast<uintptr_t>(method)-1);auto object=static_cast<Object*>(self);
 switch(key){
 case Main:return &entity;case Model:return self==&targetEntity?&targetGo:&go;case ModelGo:return self;
 case Name:return object?&object->name:nullptr;case GoTransform:return self==&targetGo?&targetRoot:&root;
 case ComponentTransform:return self==&body?&root:self==&targetBody?&targetRoot:&weaponRoot;
 case Components:return self==&targetGo?&targetArray:&array;case Length:return Box(self==&targetArray?1:2);
 case Item:return self==&targetArray?&targetBody:*static_cast<int*>(args[0])==0?&body:&weapon;
 case ChildCount:return Box(static_cast<int>(object->children.size()));
 case Child:return object->children.at(*static_cast<int*>(args[0]));
 case Parent:return object->parent;case Alive:return Box(args[0]!=nullptr);
 case LocalRotation:return Box(object->rotation);
 case Position:if(Arm(object)||object->hierarchical)return Box(WorldPosition(object));if(self==&head)return Box(PoseMath::Vector3{head.position.x+root.position.x,head.position.y+root.position.y,head.position.z+root.position.z});
  if(self==&targetHead)return Box(PoseMath::Vector3{targetHead.position.x+targetRoot.position.x,targetHead.position.y+targetRoot.position.y,targetHead.position.z+targetRoot.position.z});return Box(object->position);
 case LocalScale:return Box(object->scale);case SetLocalScale:object->scale=*static_cast<PoseMath::Vector3*>(args[0]);return nullptr;case LocalPosition:return Box(object->position);case WorldRotation:return Box(World(object));
 case SetPosition:case SetLocalPosition:if(failTargetPlacement&&self==&targetRoot){*exception=&entity;return nullptr;}object->position=*static_cast<PoseMath::Vector3*>(args[0]);return nullptr;
 case SetWorldRotation:if(self==failedArm){*exception=&entity;return nullptr;}object->rotation=*static_cast<PoseMath::Quaternion*>(args[0]);return nullptr;
 case EntityValid:return Box(true);case Movement:return movementUnavailable?nullptr:self;
 case Moving:return Box(self==&targetEntity?partnerMoving:controlledMoving);
 case Airborne:return Box(self==&targetEntity&&partnerAirborne);
 case MoveMode:return Box(0);
 case Player:return &manager;case Loading:return Box(false);case SlotCount:return Box(targetPresent?2:1);
 case Member:return *static_cast<int*>(args[0])==0?&entity:&targetEntity;
 case SetLocalRotation:if(failWrite||self==failedArm||(failPartner&&self==&targetHead)){*exception=&entity;return nullptr;}object->rotation=*static_cast<PoseMath::Quaternion*>(args[0]);++writes;return nullptr;
 default:return nullptr;
 }
}
void* BE_CALL Field(void*,const void*,void*){return &manager;}
void* BE_CALL Unbox(void*,void* value){return value;}
int BE_CALL Copy(void*,const void* value,char* target,size_t size){const auto& s=*static_cast<const std::string*>(value);strncpy_s(target,size,s.c_str(),_TRUNCATE);return int(s.size());}
uint32_t BE_CALL Pin(void*,void*,int){++pins;return static_cast<uint32_t>(pins);}
void BE_CALL Free(void*,uint32_t){--pins;}
uint64_t BE_CALL Acquire(const void* root,const char*){if(leaseBusy||root==busyRoot||owners.contains(root))return 0;token=++sequence;owners[root]=token;return token;}
int BE_CALL Owns(const void* root,const char*,uint64_t t){auto it=owners.find(root);return t&&it!=owners.end()&&it->second==t;}
int BE_CALL Release(const void* root,const char*,uint64_t t){if(Owns(root,nullptr,t)){owners.erase(root);token=owners.empty()?0:owners.begin()->second;return 1;}return 0;}
void Check(bool ok,const char* name){if(!ok){++failures;std::fprintf(stderr,"FAIL: %s\n",name);}}
}
int main(){
 std::set_terminate([]{try{if(auto e=std::current_exception())std::rethrow_exception(e);}catch(const std::exception& e){std::fprintf(stderr,"Unhandled test exception: %s\n",e.what());}std::abort();});
 using namespace Fake;
 BE_HostApiV1 helpers{};helpers.runtime_invoke=Invoke;helpers.object_unbox=Unbox;helpers.copy_managed_string=Copy;helpers.gchandle_new=Pin;helpers.gchandle_free=Free;helpers.field_get_value_object=Field;
 BE_PoseLeaseApiV1 leaseApi{1,Acquire,Owns,Release};runtime=&helpers;leases=&leaseApi;poseContracts=true;unityThread=GetCurrentThreadId();animator.type_object=&body;
 for(size_t i=0;i<std::size(methods);++i)methods[i].resolved.method_info=reinterpret_cast<void*>(i+1);
 root.children={&neck};neck.parent=&root;neck.children={&head};head.parent=&neck;
 Check(BeginPose(),"verified Perlica body can bind despite a weapon Animator");
 for(int i=0;i<600;++i)ApplyPose();
 Check(PoseMath::SameRotation(head.rotation,PoseMath::Yaw20()),"real module does not accumulate yaw over 600 frames");
 StopPose("test toggle",true);Check(PoseMath::SameRotation(head.rotation,{}),"toggle restores last unmodified animation pose");
 Check(pins==0&&token==0,"toggle releases all GC handles and pose lease");
 Check(BeginPose(),"can start a second session");ApplyPose();
 PoseMath::Quaternion animated{0.1f,0,0,0.995f};PoseMath::Normalize(animated);head.rotation=animated;ApplyPose();StopPose("fresh animator",true);
 Check(PoseMath::SameRotation(head.rotation,animated),"restore uses current animated base, not activation snapshot");
 Check(BeginPose(),"bind before external animation");ApplyPose();head.rotation={};const int before=writes;StopPose("already animated",true);
 Check(writes==before,"restore never overwrites a fresh animator pose");
 go.name="chr_other(Clone)";Check(!BeginPose(),"other characters are rejected");Check(pins==0,"rejected character releases GC handles");go.name="chr_0003_endminf_postmodel(Clone)#test";
 leaseBusy=true;Check(!BeginPose(),"existing pose owner prevents modification");Check(pins==0,"busy pose releases GC handles");leaseBusy=false;
 Object duplicate{"Bip001_Head",&neck};neck.children.push_back(&duplicate);Check(!BeginPose(),"duplicate Head bones are refused");neck.children.pop_back();
 Check(BeginPose(),"bind for failed setter");failWrite=true;ApplyPose();failWrite=false;Check(!pose.pins&&pins==0&&token==0,"setter failure stops and releases resources");
 Check(BeginPose(),"bind for focus/character cleanup");ApplyPose();pose.started=GetTickCount64()-11000;PumpPose();Check(!pose.pins&&pins==0&&token==0,"timeout/focus cleanup clears control");
 lookContracts=true;squad.field_info=&manager;
 targetRoot.children={&targetNeck};targetNeck.parent=&targetRoot;targetNeck.children={&targetHead};targetHead.parent=&targetNeck;
 targetHead.position={2,0,2};head.rotation={};
 Check(BeginPose(Mode::LookAt),"LookAt binds scanned squad Endministrator head");
 ApplyPose();Check(pose.yaw>0&&pose.yaw<45,"LookAt starts smoothly toward right target");
 for(int i=0;i<600;++i)ApplyPose();
 Check(std::abs(pose.yaw-45)<0.01f,"LookAt converges without accumulating angle");
 targetHead.position={-2,1,2};for(int i=0;i<100;++i)ApplyPose();
 Check(pose.yaw<0&&pose.pitch<0,"moving target changes yaw and pitch");
 targetPresent=false;ApplyPose();Check(!pose.pins&&pins==0&&token==0,"target leaving squad stops and releases control");
 Check(!BeginPose(Mode::LookAt)&&pins==0,"missing LookAt target cannot start");targetPresent=true;
 targetHead.position={0,0,30};Check(BeginPose(Mode::LookAt),"distant gaze target can start");StopPose("distant gaze cleanup",true);
 targetHead.position={2,0,2};targetRoot.rotation=PoseMath::YawPitch(180,0);targetHead.rotation={};head.rotation={};
 Check(BeginPose(Mode::Mutual)&&owners.size()==2,"mutual mode acquires both Animator leases");
 ApplyPose();Check(pose.wrote&&pose.reverse.wrote&&pose.yaw>0&&pose.reverse.yaw>0,"both characters turn in their own body frames");
 for(int i=0;i<600;++i)ApplyPose();Check(std::abs(pose.yaw-45)<0.01f&&std::abs(pose.reverse.yaw-45)<0.01f,"both heads converge without accumulated rotation");
 StopPose("both stop",true);Check(PoseMath::SameRotation(head.rotation,{})&&PoseMath::SameRotation(targetHead.rotation,{})&&pins==0&&owners.empty(),"both heads restore and both leases/handles release");
 busyRoot=&targetRoot;Check(!BeginPose(Mode::Mutual)&&pins==0&&owners.empty(),"partner lease conflict rolls back first lease");busyRoot=nullptr;
 Check(BeginPose(Mode::Mutual),"bind both for partner setter failure");failPartner=true;ApplyPose();failPartner=false;
 Check(!pose.pins&&pins==0&&owners.empty()&&PoseMath::SameRotation(head.rotation,{}),"partner setter failure restores first write and releases both");
 Check(BeginPose(Mode::Mutual),"bind both for target removal");ApplyPose();targetPresent=false;ApplyPose();targetPresent=true;
 Check(!pose.pins&&pins==0&&owners.empty()&&PoseMath::SameRotation(targetHead.rotation,{}),"target removal restores both sides");
 Check(BeginPose(Mode::Mutual),"bind both for partner ownership loss");ApplyPose();owners.erase(&targetRoot);targetHead.rotation=PoseMath::Yaw20();ApplyPose();
 Check(!pose.pins&&pins==0&&owners.empty()&&PoseMath::SameRotation(targetHead.rotation,PoseMath::Yaw20()),"lost partner ownership preserves outsider pose and stops whole interaction");
 standingContracts=true;movementContracts=true;root.position={};targetRoot.position={2,0,0};root.rotation={};targetRoot.rotation={};head.position={0,1.5f,0};targetHead.position={0,1.5f,0};head.rotation={};targetHead.rotation={};
 Check(BeginPose(Mode::Standing),"standing binds nearby level-ground pair");
 for(int i=0;i<60;++i)ApplyPose();
 Check(PoseMath::SamePosition(targetRoot.position,{0,0,1.2f}),"standing converges to 1.2m spacing");
 Check(PoseMath::SameRotation(root.rotation,{})&&PoseMath::SameRotation(targetRoot.rotation,PoseMath::YawPitch(180,0)),"models face each other");
 StopPose("standing restore",true);
 Check(PoseMath::SamePosition(targetRoot.position,{2,0,0})&&PoseMath::SameRotation(root.rotation,{})&&PoseMath::SameRotation(targetRoot.rotation,{})&&owners.empty()&&pins==0,"both roots restore placement and release resources");
 Check(BeginPose(Mode::Standing),"standing bind before partner placement failure");failTargetPlacement=true;ApplyPose();failTargetPlacement=false;
 Check(!pose.pins&&PoseMath::SameRotation(root.rotation,{})&&owners.empty()&&pins==0,"partner placement failure rolls back first root");
 targetRoot.position={2,0.4f,0};Check(BeginPose(Mode::Standing),"uneven starting levels accepted");ApplyPose(0);Check(PoseMath::SamePosition(targetRoot.position,{0,0,1.2f}),"uneven partner places at controlled height immediately");StopPose("uneven placement cleanup",true);targetRoot.position={4,0,0};Check(BeginPose(Mode::Standing),"far starting placement accepted");StopPose("far standing cleanup",true);
 targetRoot.position={2,0,0};partnerMoving=true;controlledMoving=true;
 Check(BeginPose(Mode::Standing),"observed true moving flags do not falsely reject idle pair");
 for(int i=0;i<60;++i)ApplyPose();Check(pose.pins&&PoseMath::SamePosition(targetRoot.position,{0,0,1.2f}),"raw moving flags cannot cancel verified visual placement");
 StopPose("regression restore",true);partnerMoving=false;controlledMoving=false;
 Check(pins==0&&owners.empty()&&PoseMath::SamePosition(targetRoot.position,{2,0,0}),"false-positive flag regression still restores roots");
 movementUnavailable=true;Check(!ReadMovement(&entity).ready,"missing movement component is reported by diagnostic");
 Check(BeginPose(Mode::Standing),"optional movement diagnostics cannot disable standing preview");StopPose("missing diagnostic restore",true);movementUnavailable=false;
 Check(!BeginPose(Mode::Handshake)&&pins==0&&owners.empty(),"handshake missing assets rejected before ownership");
 handshakeA.frames.assign(303,Handshake::Frame{{0,0,1},{0,0,1}});handshakeB.frames=handshakeA.frames;
 Check(!BeginPose(Mode::Handshake)&&pins==0&&owners.empty(),"handshake missing arm mapping releases handles");
 Object upper{"Bip001_R_UpperArm",&root},fore{"Bip001_R_Forearm",&upper},hand{"Bip001_R_Hand",&fore};
 Object otherUpper{"Bip001_R_UpperArm",&targetRoot},otherFore{"Bip001_R_Forearm",&otherUpper},otherHand{"Bip001_R_Hand",&otherFore};
 Object finger{"Bip001_R_Finger2",&hand},otherFinger{"Bip001_R_Finger2",&otherHand};hand.children={&finger};otherHand.children={&otherFinger};finger.position={0.1f,0,0};otherFinger.position={0.1f,0,0};
 root.children.push_back(&upper);upper.children={&fore};fore.children={&hand};targetRoot.children.push_back(&otherUpper);otherUpper.children={&otherFore};otherFore.children={&otherHand};
 upper.position={0,1.3f,0};fore.position={0.3f,0,0};hand.position={0.3f,0,0};otherUpper.position={0,1.3f,0};otherFore.position={0.3f,0,0};otherHand.position={0.3f,0,0};
 Check(BeginPose(Mode::Handshake)&&pose.arms.size()==6&&owners.size()==2,"paired right-arm and hand binding owns both bodies");
 for(int i=0;i<90;++i)ApplyPose();
 Check(pose.pins&&pose.arms[0].wrote&&pose.arms[5].wrote,"both arms receive same playback clock");
 auto palmA=PoseMath::Lerp(WorldPosition(&hand),WorldPosition(&finger),0.5f),palmB=PoseMath::Lerp(WorldPosition(&otherHand),WorldPosition(&otherFinger),0.5f);
 Check(Handshake::Length(Handshake::Sub(palmA,palmB))<0.0001f,"hierarchical transforms place both palm proxies on shared target");
 auto stableUpper=upper.rotation;for(int i=0;i<30;++i){upper.rotation=PoseMath::YawPitch(i%2?25:-25,0);fore.rotation=PoseMath::YawPitch(i%2?-20:20,0);ApplyPose();}
 Check(PoseMath::SameRotation(upper.rotation,stableUpper),"alternating Animator twists cannot jitter fixed reference output");
 StopPose("handshake test stop",true);
 Check(PoseMath::SameRotation(upper.rotation,PoseMath::YawPitch(25,0))&&PoseMath::SameRotation(fore.rotation,PoseMath::YawPitch(-20,0))&&PoseMath::SameRotation(otherUpper.rotation,{})&&PoseMath::SameRotation(otherFore.rotation,{})&&pins==0&&owners.empty(),"fresh Animator bases and all partner arm bones restore and leases release");
 upper.rotation={};fore.rotation={};
 Check(BeginPose(Mode::Handshake),"bind before partner arm write failure");failedArm=&otherFore;for(int i=0;i<80&&pose.pins;++i)ApplyPose();failedArm=nullptr;
 Check(!pose.pins&&pins==0&&owners.empty()&&PoseMath::SameRotation(upper.rotation,{}),"partner arm failure rolls back preceding arm writes");
 Check(BeginPose(Mode::Handshake),"bind for playback completion");for(int i=0;i<1400&&pose.pins;++i)ApplyPose();
 Check(!pose.pins&&pins==0&&owners.empty(),"clip completion automatically restores and releases");
 // Reproduce real-client failure: short arms and opposing right-shoulder offsets.
 upper.position={0.18f,1.3f,0};otherUpper.position={0.18f,1.4f,0};fore.position={0.18f,0,0};otherFore.position={0.18f,0,0};hand.position={0.16f,0,0};otherHand.position={0.16f,0,0};
 Check(BeginPose(Mode::Handshake),"short-arm pair binds with measured lateral shoulder offsets");
 for(int i=0;i<120&&pose.pins;++i)ApplyPose();
 palmA=PoseMath::Lerp(WorldPosition(&hand),WorldPosition(&finger),0.5f);palmB=PoseMath::Lerp(WorldPosition(&otherHand),WorldPosition(&otherFinger),0.5f);
 Check(pose.pins&&Handshake::Length(Handshake::Sub(palmA,palmB))<0.0001f,"adaptive anchors keep short arms reachable and palms in contact");
 StopPose("short-arm cleanup",true);Check(pins==0&&owners.empty(),"short-arm preview cleanup releases pair");
 std::vector<Object> digits;digits.reserve(40);
 for(int actor=0;actor<2;++actor){auto palm=actor?&otherHand:&hand;auto middle=actor?&otherFinger:&finger;
  for(int digit=0;digit<5;++digit){std::string prefix="Bip001_R_Finger"+std::to_string(digit);Object* previous=middle;
   if(digit!=2){digits.push_back(Object{prefix,palm});previous=&digits.back();previous->position={0.1f,float(2-digit)*0.015f,0};palm->children.push_back(previous);}
   for(const std::string& suffix:{std::string("1"),std::string("2"),std::string("Nub")}){digits.push_back(Object{prefix+suffix,previous});auto node=&digits.back();node->position={0.025f,0,0};previous->children.push_back(node);previous=node;}
  }
 }
 Check(BeginPose(Mode::Handshake)&&pose.fingers.size()==30,"complete finger geometry calibrates 30 grip joints");
 for(int i=0;i<110&&pose.pins;++i)ApplyPose();
 Check(pose.pins&&pose.fingers[0].wrote&&!PoseMath::SameRotation(finger.rotation,{}),"grip curls progressively after contact");
 palmA=PoseMath::Lerp(WorldPosition(&hand),WorldPosition(&finger),0.5f);palmB=PoseMath::Lerp(WorldPosition(&otherHand),WorldPosition(&otherFinger),0.5f);
 Check(Handshake::Length(Handshake::Sub(palmA,palmB))<0.0001f,"palm roll and finger curling retain contact");
 StopPose("grip restore",true);bool fingersRestored=true;for(auto& node:digits)fingersRestored=fingersRestored&&PoseMath::SameRotation(node.rotation,{});
 Check(fingersRestored&&PoseMath::SameRotation(finger.rotation,{})&&pins==0&&owners.empty(),"all grip joints and resources restore");
 Check(BeginPose(Mode::Handshake),"grip binds before failed finger setter");failedArm=&finger;for(int i=0;i<90&&pose.pins;++i)ApplyPose();failedArm=nullptr;
 Check(!pose.pins&&pins==0&&owners.empty()&&PoseMath::SameRotation(upper.rotation,{}),"finger write failure restores pair and releases leases");
 Check(BeginPose(Mode::Handshake),"bind for live parameter update");
 Grip::Settings live;live.values[0]=2.5f;live.values[5]=20;live.values[12]=15;
 auto liveJson=std::string("{\"grip_values\":\"")+live.Encode()+"\"}";
 Check(Configure(liveJson.c_str())==BE_Result_Ok,"persisted configuration callback accepts live profile");
 for(int i=0;i<240&&pose.pins;++i)ApplyPose();
 palmA=PoseMath::Lerp(WorldPosition(&hand),WorldPosition(&finger),0.5f);palmB=PoseMath::Lerp(WorldPosition(&otherHand),WorldPosition(&otherFinger),0.5f);
 auto expectedOffset=PoseMath::Rotate(World(&root),{0.025f,0,0});
 Check(pose.pins&&Handshake::Length(Handshake::Sub(Handshake::Sub(palmA,palmB),expectedOffset))<0.0001f,"live offset and wrist roll preserve requested palm relationship without rebind");
 auto previousProfile=gripTarget.values;Configure("{\"grip_values\":\"bad\"}");Check(gripTarget.values==previousProfile,"invalid saved profile cannot overwrite live settings");
 StopPose("live tuning cleanup",true);gripTarget=Grip::Settings{};gripCurrent=gripTarget;
 BE_ThirdPartyHostV1 transport{};transport.reply=Reply;host=&transport;hook=0;
 Check(Message("tune","{\"command\":\"tune_on\"}")==BE_Result_Ok&&calibrationMode,"explicit calibration opt-in accepted without Unity work");
 Check(BeginPose(Mode::Handshake),"bind for calibration focus handling");pose.started=GetTickCount64()-35000;PumpPose();
 Check(pose.pins&&owners.size()==2,"calibration focus loss and ordinary 30s timeout retain valid owned pose");
 Message("tune","{\"command\":\"tune_off\"}");PumpPose();
 Check(!pose.pins&&owners.empty()&&pins==0,"leaving calibration restores ordinary focus/timeout cleanup");
 Check(Message("test","{\"command\":\"arm_lookat\"}")==BE_Result_Ok&&replyResult==BE_Result_NotReady&&replyBody.find("pose_unavailable")!=std::string::npos,"business failure details survive Host transport");
 hook=1;Targets();Check(targetChoices.size()==1&&targetChoices.at(1)==targetGo.name,"target discovery excludes controlled actor and returns instantiated partner");
 Check(Message("select","{\"command\":\"select_target\",\"target_slot\":1}")==BE_Result_Ok&&replyResult==BE_Result_Ok&&selectedModel==targetGo.name&&!armed,"select discovered target and require rearming");
 Check(BeginPose(Mode::Handshake),"explicit selected partner binds compatible skeleton");
 Message("select","{\"command\":\"select_target\",\"target_slot\":1}");Check(replyResult==BE_Result_Conflict,"cannot change partner during active pose");StopPose("selection cleanup",true);
 auto savedName=targetGo.name;targetGo.name="chr_other_postmodel(Clone)";
 Check(!BeginPose(Mode::Handshake)&&pins==0&&owners.empty(),"changed slot identity rejected without leaked pose leases");
 Targets();Message("select","{\"command\":\"select_target\",\"target_slot\":1}");Check(BeginPose(Mode::Handshake),"other discovered character identity uses verified compatible skeleton");StopPose("generic target cleanup",true);targetGo.name=savedName;
 Message("select","{\"command\":\"select_target\",\"target_slot\":99}");Check(replyResult==BE_Result_InvalidArgument,"unknown target slot rejected");selectedSlot=-1;selectedModel.clear();targetChoices.clear();hook=0;
 selectedIdentity.clear();Presets::Bank testBank;testBank.enabled=true;testBank.slots[0].enabled=true;testBank.slots[0].name="handshake";testBank.slots[0].grip.values[0]=1.5f;testBank.slots[1]=testBank.slots[0];testBank.slots[1].animation="mutual";
 Presets::Bank decoded;Check(decoded.Read(testBank.Encode())&&decoded.slots[0].grip.values[0]==1.5f,"preset bank roundtrip includes roles, action and calibration");auto validBank=decoded.Encode();auto bad=validBank;bad["slots"][0]["animation"]="unknown_clip";Check(!decoded.Read(bad)&&decoded.Encode()==validBank,"invalid animation import leaves previous bank intact");bad=validBank;bad["slots"][1]["controlled"]="chr_other";Check(!decoded.Read(bad),"unsupported controlled identity rejected");bad=validBank;bad["slots"].erase(0);Check(!decoded.Read(bad),"partial bank rejected atomically");
 auto legacy=validBank;legacy["schema"]=1;legacy["slots"].erase(8);for(auto& slot:legacy["slots"]){slot["controlled"]="chr_0004_pelica";slot["target"]="chr_0003_endminf";}Presets::Bank migrated;Check(migrated.Read(legacy)&&!migrated.enabled&&migrated.slots.size()==9&&migrated.slots[0].controlled=="chr_0003_endminf"&&migrated.slots[0].target=="chr_0004_pelica"&&migrated.slots[0].grip.values[21]==1.5f,"legacy eight-slot migration reverses actor calibration and disables changed shortcuts");
 presetBank=testBank;presetKeys.fill(false);std::array<bool,9> keys{};keys[0]=true;PumpPresetKeys(keys,false);Check(!pose.pins,"background shortcut cannot start pose");PumpPresetKeys(keys,true);Check(!pose.pins,"held key on focus return does not activate");keys.fill(false);PumpPresetKeys(keys,true);keys[0]=true;PumpPresetKeys(keys,true);Check(pose.pins&&pose.mode==Mode::Handshake&&activePreset==0&&gripCurrent.values[0]==1.5f,"Numpad1 rising edge applies full preset and starts handshake");PumpPresetKeys(keys,true);Check(bool(pose.pins),"held hotkey does not toggle repeatedly");keys[1]=true;PumpPresetKeys(keys,true);Check(pose.pins&&pose.mode==Mode::Mutual&&activePreset==1&&owners.size()==2,"other shortcut restores old animation and starts next preset");pose.started=GetTickCount64()-200000;PumpPose();Check(pose.pins&&activePreset==1,"switched preset ignores focus loss and timeout");keys.fill(false);PumpPresetKeys(keys,true);keys[1]=true;PumpPresetKeys(keys,true);Check(!pose.pins&&owners.empty()&&pins==0,"same shortcut toggles off and releases resources");
 presetBank.slots[8]=testBank.slots[0];keys.fill(false);PumpPresetKeys(keys,true);keys[8]=true;PumpPresetKeys(keys,true);Check(pose.pins&&activePreset==8,"ninth numpad slot starts");keys.fill(false);PumpPresetKeys(keys,true);keys[8]=true;PumpPresetKeys(keys,true);Check(!pose.pins&&owners.empty(),"ninth numpad slot toggles off");
 auto oldTarget=targetGo.name;targetGo.name="chr_missing_postmodel(Clone)";TriggerPreset(0);Check(!pose.pins&&pins==0,"missing preset partner rejects without resources");targetGo.name=oldTarget;presetBank.enabled=false;keys.fill(false);PumpPresetKeys(keys,true);keys[0]=true;PumpPresetKeys(keys,true);Check(!pose.pins,"master disabled prevents shortcuts");presetBank=Presets::Bank{};selectedIdentity.clear();armed=false;activePreset=-1;
 using PA=InteractionPanel::Action;active=true;hook=1;lastControlled="chr_0003_endminf";Targets();gripTarget.values[0]=2.0f;
 workflow.draft.grip=gripTarget;Check(workflow.Prepare(),"prepare calibration snapshot before assigning slot");PanelExecute({PA::Capture,0});Check(presetBank.slots[0].enabled&&presetBank.slots[0].grip.values[0]==2.0f,"overlay captures live grip into preset without Unity writes on UI thread");
 PanelExecute({PA::Grip,0,100.f});Check(gripTarget.values[0]==2.0f,"overlay rejects out-of-range grip");PanelExecute({PA::Grip,0,3.0f});Check(gripTarget.values[0]==3.0f,"overlay live slider updates desired pose");
 PanelExecute({PA::Target,0});Check(presetBank.slots[0].target=="chr_0004_pelica","overlay selects scanned target identity");PanelExecute({PA::Start,0});Check(pendingStart==0&&!pose.pins,"overlay queues start instead of touching Unity objects");PanelExecute({PA::Stop});Check(pendingStart==-1&&pendingPreset==-1&&restoreRequested,"overlay stop cancels queued starts");restoreRequested=false;
 Check(!InteractionPanel::PreviewReady(true,true,false)&&!InteractionPanel::PreviewReady(false,false,false)&&!InteractionPanel::PreviewReady(true,false,true)&&InteractionPanel::PreviewReady(true,false,false),"preview waits until panel closes and launch click releases");
 Check(InteractionPanel::PreviewReady(false,false,true,true)&&InteractionPanel::PreviewReady(false,true,false,true),"calibration starts in background and while overlay remains open");
 calibrationMode=false;PanelExecute({PA::Preview});Check(pendingPreview&&calibrationMode,"calibration play enables background editing before queueing");pendingPreview=false;
 auto panelState=PanelRead();Check(panelState.connected&&panelState.grip[0]==3.0f&&panelState.slots.size()==9,"overlay snapshot includes runtime roles and calibration");
 Check(InteractionPanel::SliderValue(0,-1.f)==-8.f&&InteractionPanel::SliderValue(3,2.f)==60.f&&InteractionPanel::SliderValue(6,1.f)==100.f,"slider math clamps all three range families");Check(!InteractionPanel::MouseCancelsPose(true,true)&&InteractionPanel::MouseCancelsPose(true,false),"overlay mouse clicks do not cancel the module pose");hook=0;pendingStart=pendingPreset=-1;active=false;
 std::ifstream animationFile(INTERACTION_EXAMPLE_PATH);auto animationData=Presets::Json::parse(animationFile);ImportedAnimation::Clip imported;Check(imported.Read(animationData)&&imported.tracks.size()==2,"animation schema validates paired bone tracks");auto middle=imported.tracks[0].Sample(.35f);Check(middle.z>0&&middle.z<.174f,"animation interpolates normalized quaternion keys");auto malformed=animationData;malformed["actors"][0]["tracks"].push_back(malformed["actors"][0]["tracks"][0]);Check(!imported.Read(malformed),"duplicate bone tracks rejected");malformed=animationData;malformed["actors"][0]["tracks"][0]["keys"][1]["time"]=0;Check(!imported.Read(malformed),"unordered keyframes rejected");Check(ImportAnimation(animationData)&&animationLibrary.count("arm_rotation_test"),"valid clip imports into library");
 presetBank.slots[0].enabled=true;presetBank.slots[0].animation="clip:arm_rotation_test";Check(PreparePreset(0)&&BeginPose(Mode::Custom)&&pose.customBones.size()>=2,"imported clip binds paired skeletons and leases");for(int i=0;i<110&&pose.pins;++i)ApplyPose();Check(pose.pins&&!PoseMath::SameRotation(fore.rotation,{}),"imported bone animation produces local rotation");StopPose("custom restore",true);Check(pins==0&&owners.empty()&&PoseMath::SameRotation(fore.rotation,{})&&PoseMath::SameRotation(otherFore.rotation,{}),"custom animation restores both actors and releases all resources");Check(PreparePreset(0)&&BeginPose(Mode::Custom),"custom clip binds before timeout test");for(int i=0;i<240&&pose.pins;++i)ApplyPose();Check(!pose.pins&&pins==0&&owners.empty(),"custom clip completion restores pair");
 auto missing=animationData;missing["id"]="missing_bone";missing["actors"][0]["tracks"][0]["bone"]="Bip001_Missing";Check(ImportAnimation(missing),"structurally valid unknown-bone clip can enter library");presetBank.slots[0].animation="clip:missing_bone";Check(PreparePreset(0)&&!BeginPose(Mode::Custom)&&pins==0&&owners.empty(),"runtime missing bone rejects without leaked leases");
 std::ifstream diagnosticFile(std::filesystem::path(INTERACTION_EXAMPLE_PATH).parent_path()/"arm_raise_diagnostic.interaction-animation.json");auto diagnosticData=Presets::Json::parse(diagnosticFile);Check(ImportAnimation(diagnosticData),"visible ten-second diagnostic imports");presetBank.slots[0].animation="clip:arm_raise_diagnostic";Check(PreparePreset(0)&&BeginPose(Mode::Custom)&&pose.customBones.size()>=4,"visible diagnostic binds upper arms and forearms");for(int i=0;i<160&&pose.pins;++i)ApplyPose();Check(pose.pins&&!PoseMath::SameRotation(upper.rotation,{})&&!PoseMath::SameRotation(otherUpper.rotation,{}),"both upper arms visibly rotate during diagnostic hold");for(int i=0;i<650&&pose.pins;++i)ApplyPose();Check(!pose.pins&&pins==0&&owners.empty()&&PoseMath::SameRotation(upper.rotation,{})&&PoseMath::SameRotation(otherUpper.rotation,{}),"long diagnostic completes and restores both upper arms");

 Workflow::State staged;staged.draft.animation="clip:arm_raise_diagnostic";staged.draft.grip.values[0]=2.5f;Presets::Bank stagedBank;Check(stagedBank.enabled&&!stagedBank.slots[0].enabled&&!staged.Apply(stagedBank,0),"hotkeys default enabled but empty slots cannot import unprepared settings");Check(staged.Prepare()&&staged.Apply(stagedBank,3),"prepared settings transfer to selected slot");auto exported=Workflow::Export(staged.prepared);Presets::Entry roundtrip;Check(Workflow::Import(exported,roundtrip)&&roundtrip.target==staged.draft.target&&roundtrip.animation==staged.draft.animation&&roundtrip.grip.values[0]==2.5f,"single calibration JSON roundtrips both roles animation and parameters");staged.Invalidate();Check(!staged.Apply(stagedBank,4),"modified calibration must be prepared again");auto invalidSetting=exported;invalidSetting["setting"]["controlled"]="chr_other";Check(!Workflow::Import(invalidSetting,roundtrip),"invalid controlled identity rejected on single-setting import");
 Check(ReorderAnimations(Presets::Json::array({"arm_raise_diagnostic","arm_rotation_test","missing_bone"}))&&animationOrder.front()=="arm_raise_diagnostic","animation order supports arbitrary valid permutation");auto savedOrder=animationOrder;Check(!ReorderAnimations(Presets::Json::array({"arm_rotation_test","arm_rotation_test","missing_bone"}))&&animationOrder==savedOrder,"duplicate reorder rejected atomically");
 auto baselineHand=hand.rotation,baselineOther=otherHand.rotation;auto baselinePosition=hand.position;gripTarget=Grip::Settings{};presetBank.slots[0].grip=gripTarget;presetBank.slots[0].animation="clip:arm_raise_diagnostic";Check(PreparePreset(0)&&BeginPose(Mode::Custom),"custom animation binds before hand calibration test");gripTarget.values[0]=3;gripTarget.values[3]=20;gripTarget.values[6]+=15;for(int i=0;i<150&&pose.pins;++i)ApplyPose();Check(pose.pins&&!PoseMath::SameRotation(hand.rotation,baselineHand)&&!PoseMath::SamePosition(hand.position,baselinePosition),"custom animation applies extra wrist rotation and palm position");auto oncePosition=hand.position;for(int i=0;i<20&&pose.pins;++i)ApplyPose();Check(PoseMath::SamePosition(hand.position,oncePosition),"custom palm offset does not accumulate each frame");StopPose("custom calibrated restore",true);Check(pins==0&&owners.empty()&&PoseMath::SameRotation(hand.rotation,baselineHand)&&PoseMath::SameRotation(otherHand.rotation,baselineOther)&&PoseMath::SamePosition(hand.position,baselinePosition),"custom calibration restores wrist and palm position");Check(DeleteAnimation("arm_raise_diagnostic")&&!animationLibrary.contains("arm_raise_diagnostic")&&presetBank.slots[0].animation=="clip:arm_raise_diagnostic","animation deletion retains preset reference for missing-animation display");Check(!BeginPose(Mode::Custom),"deleted animation cannot start new pose");
 workflow.ready=true;workflow.prepared=roundtrip;active=true;PanelExecute({PA::Grip,3,10});Check(!workflow.ready,"native slider invalidates prepared snapshot");PanelExecute({PA::Reset,-2});Check(gripTarget.Encode()==Grip::Settings{}.Encode(),"reset all restores bone defaults");active=false;

 boneTarget=Bones::Settings{};workflow.draft.target="chr_0004_pelica";ScanBoneCatalog();Check(boneCatalog.size()>10,"paired catalog finds live roots body arms and finger hierarchy");{Pins referencePins;std::vector<Pose::FullBone> referenceBones;Check(WalkBones(&root,0,referencePins,referenceBones)&&WalkBones(&targetRoot,1,referencePins,referenceBones),"reference enumerates both skeletons");auto beforeWrites=writes;auto reference=CaptureSkeletonReference(referenceBones);Check(reference["pose_kind"]=="current_gameplay_pose_not_bind_pose"&&reference["bones"].size()==referenceBones.size()&&writes==beforeWrites,"reference captures both actors rotations positions without writing transforms");Check(BeginPose(),"reference guard test starts pose");bool rejected=false;try{CaptureSkeletonReference(referenceBones);}catch(...){rejected=true;}Check(rejected,"reference refuses active overridden pose");StopPose("reference guard test",true);}std::string headKey="0|Bip001_Neck[0]/Bip001_Head[0]";auto foundHead=std::find_if(boneCatalog.begin(),boneCatalog.end(),[&](auto& b){return b.key==headKey;});Check(foundHead!=boneCatalog.end(),"full hierarchy uses stable relative name paths rather than memory addresses");Bones::Settings fullSettings;auto rootOffset=Bones::Defaults();rootOffset[0]=10;rootOffset[8]=1.25f;auto headOffset=Bones::Defaults();headOffset[5]=15;Check(fullSettings.Set("0|@root",rootOffset)&&fullSettings.Set(headKey,headOffset),"full bone settings accept position rotation scale");auto snapshot=fullSettings.Encode();auto badBones=snapshot;badBones[headKey][6]=0;Check(!fullSettings.Read(badBones)&&fullSettings.Encode()==snapshot,"invalid zero scale rejected atomically");auto beforeHead=head.rotation;auto beforeRootPosition=root.position,beforeScale=root.scale;boneTarget=fullSettings;Check(BeginPose(),"full bone offsets bind before leases and head preview");for(int i=0;i<180&&pose.pins;++i){RemoveBoneLayer(true);ApplyPose();ApplyBoneLayer();}Check(pose.pins&&std::abs(root.position.x-beforeRootPosition.x-.1f)<.00001f&&std::abs(root.scale.z-beforeScale.z*1.25f)<.00001f,"root offset and scale do not accumulate over 180 frames");auto expectedHead=PoseMath::Multiply(PoseMath::Multiply(beforeHead,PoseMath::Yaw20()),Handshake::XYZ(0,0,15));Check(PoseMath::SameRotation(head.rotation,expectedHead),"full bone layer composes with existing animation without contaminating its baseline");StopPose("all bone restore",true);Check(pins==0&&owners.empty()&&PoseMath::SamePosition(root.position,beforeRootPosition)&&PoseMath::SamePosition(root.scale,beforeScale)&&PoseMath::SameRotation(head.rotation,beforeHead),"stop restores full bone layer and existing animation layers");
 Workflow::State allBoneState;allBoneState.draft.bones=fullSettings;Check(allBoneState.Prepare(),"full skeleton offsets prepare for export");Presets::Entry importedBoneEntry;Check(Workflow::Import(Workflow::Export(allBoneState.prepared),importedBoneEntry)&&importedBoneEntry.bones.Encode()==snapshot,"single calibration JSON preserves all bone axes");Presets::Bank fullBank;Check(allBoneState.Apply(fullBank,8),"all bone calibration can fill numpad nine");Presets::Bank fullRoundtrip;Check(fullRoundtrip.Read(fullBank.Encode())&&fullRoundtrip.slots[8].bones.Encode()==snapshot,"numpad bank roundtrip preserves full skeleton");

 auto scaleMethod=methods[LocalScale].resolved.method_info;methods[LocalScale].resolved.method_info=nullptr;boneTarget=fullSettings;Check(!BeginPose()&&pins==0&&owners.empty(),"missing scale API rejects requested scale without changing pose");methods[LocalScale].resolved.method_info=scaleMethod;boneTarget=Bones::Settings{};auto partnerOffset=Bones::Defaults();partnerOffset[1]=5;partnerOffset[3]=20;partnerOffset[6]=.8f;Check(boneTarget.Set("1|@root",partnerOffset)&&BeginPose(Mode::Standing),"partner full root calibration binds both owned roots");auto partnerBaselineScale=targetRoot.scale;for(int i=0;i<90&&pose.pins;++i){RemoveBoneLayer(true);ApplyPose();ApplyBoneLayer();}Check(pose.pins&&std::abs(targetRoot.scale.x-partnerBaselineScale.x*.8f)<.00001f,"partner scale follows its own calibration");StopPose("partner root calibration restore",true);Check(pins==0&&owners.empty()&&PoseMath::SamePosition(targetRoot.scale,partnerBaselineScale),"partner root scale restores before releasing dual leases");
 boneTarget=Bones::Settings{};Check(boneTarget.Set("0|missing[0]",headOffset)&&!BeginPose()&&pins==0&&owners.empty(),"missing configured bone fails before acquiring resources");boneTarget=Bones::Settings{};Check(Message("bones-page","{\"command\":\"bones_get\",\"offset\":0}")==BE_Result_Ok&&Presets::Json::parse(replyBody).contains("bones"),"bone metadata pages are exposed to UI");auto boneMessage=Presets::Json{{"command","bone_set"},{"key",headKey},{"field",5},{"value",25},{"generation",boneGeneration}}.dump();Check(Message("bones-value",boneMessage.c_str())==BE_Result_Ok&&replyResult==BE_Result_Ok&&boneTarget.Get(headKey)[5]==25,"live UI bone update targets scanned key");auto stale=Presets::Json::parse(boneMessage);stale["generation"]=boneGeneration+1;Message("stale",stale.dump().c_str());Check(replyResult!=BE_Result_Ok&&boneTarget.Get(headKey)[5]==25,"stale skeleton page cannot update new actor mapping");boneTarget=Bones::Settings{};
 bool uiOpen=false,previousF8=false;Check(InteractionPanel::ToggleOpen(true,true,previousF8,uiOpen)&&uiOpen,"F8 edge opens UI");Check(!InteractionPanel::ToggleOpen(true,true,previousF8,uiOpen)&&uiOpen,"held F8 does not close UI");InteractionPanel::ToggleOpen(false,true,previousF8,uiOpen);Check(InteractionPanel::ToggleOpen(true,true,previousF8,uiOpen)&&!uiOpen,"second F8 edge closes UI");Check(!InteractionPanel::GameInputAllowed(true,true)&&InteractionPanel::GameInputAllowed(true,false),"editing UI excludes gameplay hotkeys and movement");animationLibrary.clear();presetBank=Presets::Bank{};
 host=nullptr;
 if(!failures)std::puts("PASS: simulated runtime binding, non-accumulation, restoration, actor rejection, lease conflict, ambiguous bones, write failure and cleanup");
 boneTarget=Bones::Settings{};selectedClip="absolute_test";
 auto absolute=Presets::Json{{"format","endfield-interaction-animation"},{"version",2},{"rotation_space","absolute_local"},{"target_character","chr_0004_pelica"},{"id","absolute_test"},{"name","absolute test"},{"duration",2},{"distance",1.2},{"actors",Presets::Json::array({{{"role","partner"},{"tracks",Presets::Json::array({{{"bone","Bip001_Head"},{"keys",Presets::Json::array({{{"time",0},{"rotation",{0,.173648f,0,.984808f}},{"position",{0,.3f,0}}},{{"time",2},{"rotation",{0,.173648f,0,.984808f}},{"position",{0,.3f,0}}}})}}})}}})}};
 ImportedAnimation::Clip absoluteClip;Check(absoluteClip.Read(absolute)&&absoluteClip.absolute&&absoluteClip.tracks.size()==1,"v2 parses one animated partner with absolute local rotation and position");auto invalidAbsolute=absolute;invalidAbsolute["actors"][0]["role"]="controlled";Check(!absoluteClip.Read(invalidAbsolute),"v2 target binding cannot be assigned to controlled actor");invalidAbsolute=absolute;invalidAbsolute["actors"][0]["tracks"][0]["keys"][1].erase("position");Check(!absoluteClip.Read(invalidAbsolute),"mixed positional key presence rejected atomically");Check(ImportAnimation(absolute),"absolute FBX result imports");presetBank.slots[0].enabled=true;presetBank.slots[0].controlled="chr_0003_endminf";presetBank.slots[0].animation="clip:absolute_test";presetBank.slots[0].target="chr_0004_pelica";presetBank.slots[0].bones=Bones::Settings{};Check(PreparePreset(0),"absolute preview selects target");auto oldTargetRotation=targetHead.rotation,oldMainRotation=head.rotation,oldMainHand=hand.rotation;auto oldTargetPosition=targetHead.position;targetHead.rotation=Handshake::XYZ(0,40,0);auto targetStart=targetHead.rotation;
 auto nearbyPartnerPosition=targetRoot.position;
 targetRoot.position={1000,50,-1000};
 Check(BeginPose(Mode::Custom),"distant party partner starts imported animation despite distance and height");
 ApplyPose(0);
 auto distantScene=SceneLayout::Build(pose.placement.anchor,pose.placement.anchorRotation,pose.partnerPlacement.anchor,pose.partnerPlacement.anchorRotation,boneTarget.Get("0|@root"),boneTarget.Get("1|@root"));Check(pose.pins&&PoseMath::SamePosition(WorldPosition(&targetRoot),distantScene.partnerPosition),"distant partner teleports to calibrated controlled placement on first frame");
 StopPose("distant partner restore",true);
 Check(PoseMath::SamePosition(targetRoot.position,{1000,50,-1000})&&pins==0&&owners.empty(),"distant partner original location is restored without leaking leases");
 targetRoot.position=nearbyPartnerPosition;
 Check(BeginPose(Mode::Custom)&&std::all_of(pose.customBones.begin(),pose.customBones.end(),[](auto& bone){return bone.actor==1&&bone.field==-1;}),"absolute FBX avoids procedural calibration bindings on controlled actor");ApplyPose(0);auto initialScene=SceneLayout::Build(pose.placement.anchor,pose.placement.anchorRotation,pose.partnerPlacement.anchor,pose.partnerPlacement.anchorRotation,boneTarget.Get("0|@root"),boneTarget.Get("1|@root"));Check(PoseMath::SamePosition(WorldPosition(&targetRoot),initialScene.partnerPosition)&&PoseMath::SameRotation(targetHead.rotation,PoseMath::Yaw20())&&std::abs(targetHead.position.y-.3f)<.00001f,"first custom frame teleports to calibrated scene and applies clip pose without sliding or idle blend");ApplyPose(.01f);Check(std::abs(pose.clipTime-.01f)<.00001f,"custom timeline advances immediately without placement delay");for(int i=0;i<65&&pose.pins;++i)ApplyPose();Check(pose.pins&&PoseMath::SameRotation(targetHead.rotation,PoseMath::Yaw20())&&std::abs(targetHead.position.y-.3f)<.00001f,"absolute pose replaces idle rotation and applies local position without accumulation");Check(PoseMath::SameRotation(head.rotation,oldMainRotation)&&PoseMath::SameRotation(hand.rotation,oldMainHand),"partner-only clip leaves controlled bones alone");StopPose("absolute test restore",true);Check(PoseMath::SameRotation(targetHead.rotation,targetStart)&&PoseMath::SamePosition(targetHead.position,oldTargetPosition)&&owners.empty()&&pins==0,"absolute rotation and translation restore on stop");targetHead.rotation=oldTargetRotation;
 Handshake::BodyFrame contactFrame{};Check(Handshake::ContactFrame({0,.2f,.98f},{1,.3f,0},{0,0,1},contactFrame),"tilted body frame builds");Check(std::abs(Handshake::Dot(contactFrame.up,contactFrame.right))<.00001f&&std::abs(Handshake::Dot(contactFrame.up,contactFrame.forward))<.00001f,"contact axes remain orthogonal despite root and spine disagreement");
 auto wristRoll=Handshake::WristLimit({},Handshake::Axis('x',100),{1,0,0});Check(PoseMath::SameRotation(wristRoll,Handshake::Axis('x',100)),"palm roll is not clamped as wrist bending");
 ImportedAnimation::Clip sliceSource;Check(sliceSource.Read(absolute),"slice source parses");auto sliceJson=ImportedAnimation::Slice(sliceSource,.25f,.75f,"test_slice","測試片段");ImportedAnimation::Clip sliced;Check(sliced.Read(sliceJson)&&std::abs(sliced.duration-.5f)<.00001f&&sliced.targetCharacter==sliceSource.targetCharacter,"slice preserves target and rebases duration");Check(PoseMath::SameRotation(sliced.tracks[0].Sample(0),sliceSource.tracks[0].Sample(.25f))&&PoseMath::SamePosition(sliced.tracks[0].SamplePosition(.5f),sliceSource.tracks[0].SamplePosition(.75f)),"fractional slice endpoints interpolate rotation and position");bool rejectedSlice=false;try{ImportedAnimation::Slice(sliceSource,.1f,.15f,"bad","bad");}catch(...){rejectedSlice=true;}Check(rejectedSlice,"invalid tiny slice refused");
 auto longJson=absolute;longJson["duration"]=7200.f;auto& longKeys=longJson["actors"][0]["tracks"][0]["keys"];auto firstLong=longKeys[0];longKeys=Presets::Json::array();for(int i=0;i<=22000;++i){auto k=firstLong;k["time"]=7200.f*i/22000.f;longKeys.push_back(k);}Check(longJson.dump().size()>1048576,"large animation regression exceeds old byte limit");ImportedAnimation::Clip longClip;Check(longClip.Read(longJson)&&longClip.duration==7200.f&&longClip.tracks[0].keys.size()==22001,"large long clip no longer rejected by duration or key ceilings");
 auto stickyModeBefore=calibrationMode;calibrationMode=false;calibrationLoop=false;Check(PreparePreset(0)&&BeginPose(Mode::Custom),"latched FBX preset starts");activePreset=0;pose.placementTime=1;pose.clipTime=pose.clip->duration+.1f;PumpPose();Check(pose.pins&&pose.loopCount>=1&&activePreset==0,"latched FBX loops past end without calibration loop");TriggerPreset(0);Check(!pose.pins&&activePreset==-1&&owners.empty(),"original preset key restores latched FBX");calibrationMode=stickyModeBefore;
 auto previousCalibrationMode=calibrationMode;auto previousSelected=selectedClip;animationLibrary["long_test"]=std::make_shared<ImportedAnimation::Clip>(longClip);selectedClip="long_test";calibrationMode=true;Check(BeginPose(Mode::Custom),"long custom animation starts");pose.started=GetTickCount64()-200000;PumpPose();Check(pose.pins&&pose.clip->duration==7200.f,"long playback not stopped by calibration wall timeout");StopPose("long test restore",true);calibrationMode=previousCalibrationMode;animationLibrary.erase("long_test");selectedClip=previousSelected;
 auto invalidManager=absolute;invalidManager["manager_action"]="unknown";Check(!absoluteClip.Read(invalidManager),"unknown manager action rejected");
 animationLibrary["absolute_test"]->managerAction="standing";Check(BeginPose(Mode::Custom),"standing layer binds without partner arm changes");head.rotation=Handshake::XYZ(0,40,0);for(int i=0;i<65&&pose.pins;++i)ApplyPose();Check(pose.pins&&PoseMath::SameRotation(head.rotation,oldMainRotation),"standing layer holds manager while partner animation plays");StopPose("standing layer restore",true);Check(PoseMath::SameRotation(head.rotation,Handshake::XYZ(0,40,0))&&pins==0&&owners.empty(),"standing layer restores fresh animator pose");head.rotation=oldMainRotation;
 animationLibrary["absolute_test"]->managerAction="waist_hold";Check(!BeginPose(Mode::Custom)&&pins==0&&owners.empty(),"missing waist refuses before acquiring any ownership");
 Object waistBone{"Bip001_Pelvis"};waistBone.parent=&targetRoot;waistBone.position={.28f,1.1f,.1f};targetRoot.children.push_back(&waistBone);Object spineBone{"Bip001_Spine"};spineBone.parent=&targetRoot;spineBone.position={.28f,1.35f,.1f};targetRoot.children.push_back(&spineBone);
 auto originalUpper=upper.rotation;Check(BeginPose(Mode::Custom)&&pose.arms.size()==3&&pose.clip->managerAction=="waist_hold","waist layer binds one manager arm");Check(Handshake::Length(Handshake::Sub(pose.partnerPlacement.anchor,pose.placement.anchor))<.5f&&PoseMath::SameRotation(pose.partnerPlacement.anchorRotation,pose.placement.anchorRotation),"waist layer uses close same-facing placement");
 for(int i=0;i<65&&pose.pins;++i)ApplyPose();auto firstUpper=upper.rotation;pose.clipPaused=true;auto frozenWaistTime=pose.clipTime;waistBone.position.x+=.04f;for(int i=0;i<20&&pose.pins;++i)ApplyPose();Check(pose.pins&&!PoseMath::SameRotation(firstUpper,upper.rotation)&&PoseMath::SameRotation(targetHead.rotation,PoseMath::Yaw20()),"waist follows moving partner without suppressing FBX tracks");Check(pose.clipTime==frozenWaistTime,"paused FBX keeps IK active without advancing source animation");auto wristDelta=PoseMath::Multiply(PoseMath::Inverse(pose.arms[2].restLocal),hand.rotation);wristDelta=PoseMath::Multiply(wristDelta,PoseMath::Inverse(Handshake::TwistFraction(wristDelta,pose.arms[2].axis,1.f)));Check(2*std::acos(std::clamp(std::abs(wristDelta.w),0.f,1.f))*57.29577951f<=60.01f,"waist wrist bend stays within configured limit");
 Check(pose.waistSpine==&spineBone,"waist contact uses actual spine rather than model root axes");auto previousHand=hand.rotation;spineBone.position={.28f,1.14f,.28f};for(int i=0;i<30&&pose.pins;++i){ApplyPose();auto step=PoseMath::Multiply(PoseMath::Inverse(previousHand),hand.rotation);Check(2*std::acos(std::clamp(std::abs(step.w),0.f,1.f))*57.29577951f<=4.1f,"tilted partner waist does not abruptly flip manager wrist");previousHand=hand.rotation;}Check(bool(pose.pins),"tilted spine remains compatible with waist tracking");
 StopPose("waist restore",true);Check(PoseMath::SameRotation(upper.rotation,originalUpper)&&pins==0&&owners.empty(),"waist stop restores manager arm and releases both actors");
 Check(BeginPose(Mode::Custom),"waist failure fixture starts");failedArm=&fore;for(int i=0;i<65&&pose.pins;++i)ApplyPose();failedArm=nullptr;Check(!pose.pins&&pins==0&&owners.empty()&&PoseMath::SameRotation(upper.rotation,originalUpper),"waist setter failure rolls back manager and partner");
 Object leftUpper{"Bip001_L_UpperArm",&root},leftFore{"Bip001_L_Forearm",&leftUpper},leftHand{"Bip001_L_Hand",&leftFore},leftFinger{"Bip001_L_Finger2",&leftHand};
 leftUpper.position={-.18f,1.3f,0};leftFore.position={-.18f,0,0};leftHand.position={-.16f,0,0};leftFinger.position={-.08f,0,0};leftUpper.children={&leftFore};leftFore.children={&leftHand};leftHand.children={&leftFinger};root.children.push_back(&leftUpper);
 for(const auto* action:{"front_waist","back_waist","head_pat"}){
  auto candidateJson=absolute;candidateJson["manager_action"]=action;Check(absoluteClip.Read(candidateJson),"new manager action schema accepted");animationLibrary["absolute_test"]->managerAction=action;
  Check(BeginPose(Mode::Custom)&&pose.arms.size()==6,"dual manager arms bind");
  auto facing=PoseMath::Multiply(PoseMath::Inverse(pose.placement.anchorRotation),pose.partnerPlacement.anchorRotation);Check(PoseMath::SameRotation(facing,PoseMath::YawPitch(std::string(action)=="back_waist"?0.f:180.f,0)),"front and back scene orientations are distinct");
  for(int i=0;i<65&&pose.pins;++i)ApplyPose();Check(pose.pins&&pose.arms[2].wrote&&pose.arms[5].wrote,"both hands receive independent updates");
  Check(pose.waist==(std::string(action)=="head_pat"?&targetHead:&waistBone),"contact targets head or pelvis by action");StopPose("dual action restore",true);Check(pins==0&&owners.empty()&&PoseMath::SameRotation(leftUpper.rotation,{}),"dual action restores and releases ownership");
 }
 root.children.pop_back();
 targetRoot.children.pop_back();targetRoot.children.pop_back();animationLibrary["absolute_test"]->managerAction="none";
 PoseMath::Vector3 previousPlane{};for(int i=-60;i<=60;++i){PoseMath::Vector3 plane{},aim{.001f,1.f,i*.001f};Check(Handshake::StablePlane(aim,{0,1,0},previousPlane,plane),"elbow plane remains valid near preferred-axis singularity");if(i>-60)Check(Handshake::Dot(plane,previousPlane)>=0,"elbow plane retains sign instead of flipping 180 degrees");previousPlane=plane;}
 InteractionPanel::SliderDrag drag;drag.active=true;drag.command={InteractionPanel::Action::BoneValue,1,0,"1|@root"};drag.initial=83;drag.low=-100;drag.high=100;drag.step=.1f;drag.pixels=200;drag.startX=300;Check(std::abs(drag.Value(306)-89)<.00001f&&drag.command.index==1&&drag.command.text=="1|@root","drag freezes original bone field and maps 83 to 89 linearly despite row rebuilds");
 auto savedMainPosition=root.position,savedPartnerPosition=targetRoot.position;auto savedMainFacing=root.rotation,savedPartnerFacing=targetRoot.rotation;
 auto rootValues=Bones::Defaults();rootValues[0]=20;rootValues[1]=5;rootValues[2]=-30;rootValues[4]=45;Check(boneTarget.Set("1|@root",rootValues),"partner root scene calibration accepted");
 root.position={10,0,20};root.rotation={};targetRoot.position={11,0,20};targetRoot.rotation={};Check(BeginPose(Mode::Custom),"scene starts from manager translated location");for(int i=0;i<65&&pose.pins;++i)ApplyPose();ApplyBoneLayer();Check(pose.pins&&PoseMath::SamePosition(targetRoot.position,{10.2f,.05f,20.9f}),"partner root XYZ uses manager frame exactly once");Check(PoseMath::SameRotation(targetRoot.rotation,PoseMath::YawPitch(225,0)),"partner root rotation composes with shared anchor");StopPose("scene A restore",true);Check(PoseMath::SamePosition(root.position,{10,0,20})&&PoseMath::SamePosition(targetRoot.position,{11,0,20}),"calibrated scene restores original placement");
 calibrationMode=true;workflow.draft.animation="clip:absolute_test";timelineDraft={};root.position={-8,0,5};root.rotation=PoseMath::YawPitch(90,0);targetRoot.position={-8,0,3};targetRoot.rotation={};Check(BeginPose(Mode::Custom),"scene restarts after manager moves and turns with partner on opposite side");for(int i=0;i<65&&pose.pins;++i){ApplyPose();ApplyBoneLayer();}auto relative=PoseMath::Rotate(PoseMath::Inverse(root.rotation),Handshake::Sub(targetRoot.position,root.position));Check(pose.pins&&PoseMath::SamePosition(relative,{.2f,.05f,.9f}),"same calibrated partner layout survives translation rotation and initial squad placement");
 auto mainValues=Bones::Defaults();mainValues[0]=10;mainValues[4]=20;boneTarget.Set("0|@root",mainValues);for(int i=0;i<10&&pose.pins;++i){ApplyPose();ApplyBoneLayer();}relative=PoseMath::Rotate(PoseMath::Inverse(root.rotation),Handshake::Sub(targetRoot.position,root.position));Check(pose.pins&&PoseMath::SamePosition(relative,{.2f,.05f,.9f}),"live manager root offset carries partner scene without accumulation"); pose.clipPaused=true;auto frozenTime=pose.clipTime;rootValues[1]=83;boneTarget.Set("1|@root",rootValues);for(int i=0;i<10;++i){ApplyPose();ApplyBoneLayer();}auto position83=targetRoot.position;rootValues[1]=89;boneTarget.Set("1|@root",rootValues);for(int i=0;i<80;++i){ApplyPose();ApplyBoneLayer();}auto deltaY=PoseMath::Rotate(PoseMath::Inverse(root.rotation),Handshake::Sub(targetRoot.position,position83));Check(pose.pins&&pose.clipTime==frozenTime&&PoseMath::SamePosition(deltaY,{0,.06f,0}),"paused root Y 83 to 89 gives exactly six centimeters without accumulation");
 Bones::Settings wideSettings;auto wide=Bones::Defaults();wide[0]=-200;wide[2]=200;Check(wideSettings.Set("1|@root",wide),"root X Z accepts doubled range");Bones::Settings wideRead;Check(wideRead.Read(wideSettings.Encode()),"expanded root range survives export import");wide[1]=101;Check(!wideSettings.Set("1|@root",wide),"root Y retains old range");wide[1]=0;wide[0]=-201;Check(!wideSettings.Set("1|@root",wide),"root X still validates expanded boundary");auto savedMainValues=mainValues;mainValues[1]=58;boneTarget.Set("0|@root",mainValues);ApplyPose();ApplyBoneLayer();auto mainAt58=root.position,partnerAt58=targetRoot.position;mainValues[1]=60;boneTarget.Set("0|@root",mainValues);for(int i=0;i<80;++i){ApplyPose();ApplyBoneLayer();}Check(std::abs(root.position.y-mainAt58.y-.02f)<.00002f&&std::abs(targetRoot.position.y-partnerAt58.y-.02f)<.00002f,"manager Y 58 to 60 carries both actors two centimeters");boneTarget.Set("0|@root",savedMainValues);ApplyPose();ApplyBoneLayer();host=&transport;for(int step=830;step<=890;++step){auto command=Presets::Json{{"command","bone_set"},{"key","1|@root"},{"field",1},{"value",step*.1f},{"generation",boneGeneration}}.dump();Check(Message("drag",command.c_str())==BE_Result_Ok&&replyResult==BE_Result_Ok,"drag update accepted through real native transport");PumpPose();auto expected=SceneLayout::Build(pose.placement.anchor,pose.placement.anchorRotation,pose.partnerPlacement.anchor,pose.partnerPlacement.anchorRotation,boneTarget.Get("0|@root"),boneTarget.Get("1|@root"));Check(pose.pins&&PoseMath::SamePosition(targetRoot.position,expected.partnerPosition),"drag transport and full pump retain linear root position");}host=nullptr;
 host=&transport;Check(Message("pause","{\"command\":\"animation_pause\",\"paused\":false}")==BE_Result_Ok&&!pose.clipPaused&&replyBody.find("time")!=std::string::npos,"pause transport resumes source clock and returns frozen time");host=nullptr;
StopPose("scene B restore",true);Check(pins==0&&owners.empty()&&PoseMath::SamePosition(root.position,{-8,0,5})&&PoseMath::SamePosition(targetRoot.position,{-8,0,3})&&PoseMath::SameRotation(root.rotation,PoseMath::YawPitch(90,0)),"shared scene offset restores both roots and leases");
 boneTarget=Bones::Settings{};root.position=savedMainPosition;targetRoot.position=savedPartnerPosition;root.rotation=savedMainFacing;targetRoot.rotation=savedPartnerFacing;
 host=&transport;active=true;workflow.draft.animation="handshake";PanelExecute({InteractionPanel::Action::DraftMotion,0,0,"clip:absolute_test"});Check(workflow.draft.animation=="clip:absolute_test","native animation menu selects explicit animation rather than cycling");PanelExecute({InteractionPanel::Action::DraftMotion,0,0,"clip:missing"});Check(workflow.draft.animation=="clip:absolute_test","native menu rejects missing animation without altering selection");
 Check(Message("loop","{\"command\":\"calibration_loop\",\"enabled\":true}")==BE_Result_Ok&&calibrationLoop,"loop selection transport accepted");calibrationMode=true;Check(BeginPose(Mode::Custom),"loop preview starts");pose.started=GetTickCount64()-200000;for(int i=0;i<220&&pose.pins;++i)PumpPose();Check(pose.pins&&pose.loopCount>=1&&owners.size()==2,"loop keeps actors and calibration alive past clip end and ordinary timeout");pose.clipPaused=true;auto loopPauseTime=pose.clipTime;for(int i=0;i<10;++i)PumpPose();Check(pose.pins&&pose.clipTime==loopPauseTime,"loop pause preserves frame");pose.clipPaused=false;pose.started=GetTickCount64();Message("loop","{\"command\":\"calibration_loop\",\"enabled\":false}");for(int i=0;i<150&&pose.pins;++i)PumpPose();Check(!pose.pins&&pins==0&&owners.empty(),"disabling loop ends current cycle and restores both actors");host=nullptr;
 host=&transport;calibrationMode=true;Check(BeginPose(Mode::Custom),"timeline fixture starts");PanelExecute({InteractionPanel::Action::Seek,0,.75f});PumpPose();Check(pose.pins&&pose.clipPaused&&pose.scrubbing&&std::abs(pose.clipTime-.75f)<.00001f,"seek queues to gameplay and freezes frame");PanelExecute({InteractionPanel::Action::Step,-1});PumpPose();Check(std::abs(pose.clipTime-(.75f-1.f/30))<.00001f,"step moves one timeline frame");PanelExecute({InteractionPanel::Action::MarkOut});PanelExecute({InteractionPanel::Action::Seek,0,.25f});PumpPose();PanelExecute({InteractionPanel::Action::MarkIn});PanelExecute({InteractionPanel::Action::RangeLoop});for(int i=0;i<100&&pose.pins;++i)PumpPose();Check(pose.pins&&pose.rangeLoop&&pose.clipTime>=pose.rangeStart&&pose.clipTime<pose.rangeEnd,"range loop remains within marked interval");PanelExecute({InteractionPanel::Action::Seek,0,100.f});PumpPose();Check(pose.pins&&pose.clipPaused&&pose.clipTime==pose.clip->duration,"scrub exact last frame without ending preview");auto countBeforeSave=animationLibrary.size();PanelExecute({InteractionPanel::Action::SliceSave,0,0,"named saved slice"});Check(animationLibrary.size()==countBeforeSave+1,"saving named slice adds one library item without external file path");auto savedSlice=animationOrder.back();Check(animationLibrary.at(savedSlice)->name=="named saved slice","saving preserves user entered clip name");auto oldDraft=workflow.draft.animation;workflow.draft.animation=oldDraft;auto exportedPath=std::filesystem::absolute("runtime-animation-export-test.json");PanelExecute({InteractionPanel::Action::ExportAnimation,0,0,exportedPath.string()});std::ifstream exportedFile(exportedPath);ImportedAnimation::Clip exportedClip;Check(exportedFile.good()&&exportedClip.Read(Presets::Json::parse(exportedFile))&&exportedClip.name==pose.clip->name+" · 片段"&&std::abs(exportedClip.duration-(pose.rangeEnd-pose.rangeStart))<.0001f&&animationLibrary.size()==countBeforeSave+1,"export selected saved slice roundtrips without duplicating library");exportedFile.close();std::filesystem::remove(exportedPath);workflow.draft.animation=oldDraft;StopPose("timeline restore",true);calibrationMode=false;host=nullptr;
 Object armTwist{"Bip001_RUpArmTwist",&otherUpper},armTwist1{"Bip001_RUpArmTwist1",&armTwist};armTwist.children={&armTwist1};otherUpper.children.push_back(&armTwist);otherUpper.rotation={};Check(BeginPose(Mode::Custom)&&pose.twists.size()==2,"FBX binds verified skinning twist branches without swapping arms");otherUpper.rotation=Handshake::Axis('x',120);for(int i=0;i<65&&pose.pins;++i)ApplyPose();Check(pose.pins&&PoseMath::SameRotation(PoseMath::Multiply(PoseMath::Inverse(targetRoot.rotation),World(&armTwist)),Handshake::Axis('x',120))&&PoseMath::SameRotation(PoseMath::Multiply(PoseMath::Inverse(targetRoot.rotation),World(&armTwist1)),Handshake::Axis('x',120)),"helpers inherit upper arm without guessed counter twist");StopPose("twist restore",true);Check(PoseMath::SameRotation(armTwist.rotation,{})&&PoseMath::SameRotation(armTwist1.rotation,{})&&pins==0&&owners.empty(),"twist helpers restore their own writes");
 otherUpper.rotation={};Check(BeginPose(Mode::Custom),"twist failure fixture starts");otherUpper.rotation=Handshake::Axis('x',120);failedArm=&armTwist1;for(int i=0;i<65&&pose.pins;++i)ApplyPose();failedArm=nullptr;Check(!pose.pins&&pins==0&&owners.empty()&&PoseMath::SameRotation(armTwist.rotation,{}),"twist setter failure rolls back preceding helper and both actor leases");otherUpper.children.pop_back();otherUpper.rotation={};
 Object mainSkeletonRoot{"Bip001",&root};mainSkeletonRoot.position={0,.95f,0};root.children.push_back(&mainSkeletonRoot);auto heldMainPosition=mainSkeletonRoot.position;Object skeletonRoot{"Bip001",&targetRoot};skeletonRoot.position={0,.93f,0};skeletonRoot.rotation=Handshake::XYZ(0,5,0);targetRoot.children.push_back(&skeletonRoot);auto heldRootPosition=skeletonRoot.position;auto heldRootRotation=skeletonRoot.rotation;Check(BeginPose(Mode::Custom),"untracked FBX skeleton root binds stabilization");pose.clipPaused=true;pose.scrubbing=true;for(int i=0;i<80;++i){mainSkeletonRoot.position={0,i%2?.55f:1.5f,0};mainSkeletonRoot.rotation=Handshake::XYZ(35,0,0);skeletonRoot.position={0,i%2?.75f:1.2f,0};skeletonRoot.rotation=Handshake::XYZ(i%2?40.f:-30.f,0,0);ApplyPose();Check(PoseMath::SamePosition(mainSkeletonRoot.position,heldMainPosition)&&PoseMath::SameRotation(mainSkeletonRoot.rotation,{})&&PoseMath::SamePosition(skeletonRoot.position,heldRootPosition)&&PoseMath::SameRotation(skeletonRoot.rotation,heldRootRotation),"paused FBX ignores game root height and tilt overwrite");}StopPose("skeleton hold restore",true);Check(std::abs(skeletonRoot.position.y-.75f)<.00001f&&PoseMath::SameRotation(skeletonRoot.rotation,Handshake::XYZ(40,0,0))&&pins==0&&owners.empty(),"skeleton hold restores latest game pose and releases leases");skeletonRoot.position={.1f,1.35f,.2f};mainSkeletonRoot.position={.2f,1.4f,.3f};Check(BeginPose(Mode::Custom),"restart after game idle pose changes");pose.clipPaused=true;pose.scrubbing=true;ApplyPose();Check(PoseMath::SamePosition(skeletonRoot.position,heldRootPosition)&&PoseMath::SamePosition(mainSkeletonRoot.position,heldMainPosition),"restart reuses same skeleton reference instead of new idle pose");StopPose("cached reference restore",true);auto references=EncodeSkeletonReferences();skeletonReferences.clear();ReadSkeletonReferences(references);Check(skeletonReferences.contains("chr_0004_pelica"),"skeleton reference cache serializes and loads");mainSkeletonRoot.position={0,.55f,0};mainSkeletonRoot.rotation=Handshake::XYZ(35,0,0);root.children.pop_back();Check(std::abs(mainSkeletonRoot.position.y-.55f)<.00001f&&PoseMath::SameRotation(mainSkeletonRoot.rotation,Handshake::XYZ(35,0,0)),"manager skeleton root restores latest game pose");targetRoot.children.pop_back();
 // Idle translation on a rotation-only child and an untracked parent must not
 // change a replay. A separate authored position channel must remain active.
 Object idleParent{"Bip001_IdleParent",&targetRoot},rotationChild{"Bip001_RotationOnly",&idleParent};
 idleParent.position={.2f,.4f,.1f};idleParent.rotation=Handshake::XYZ(0,12,0);rotationChild.position={.1f,.25f,0};idleParent.children={&rotationChild};targetRoot.children.push_back(&idleParent);
 auto chainJson=absolute;chainJson["id"]="idle_chain_test";chainJson["actors"][0]["tracks"].push_back({{"bone","Bip001_RotationOnly"},{"keys",Presets::Json::array({{{"time",0},{"rotation",{0,0,0,1}}},{{"time",2},{"rotation",{0,0,0,1}}}})}});
 Check(ImportAnimation(chainJson),"idle-chain fixture imports");selectedClip="idle_chain_test";
 auto parentPosition=idleParent.position,childPosition=rotationChild.position;auto parentRotation=idleParent.rotation;
 Check(BeginPose(Mode::Custom),"idle-chain first playback");pose.clipPaused=true;pose.scrubbing=true;ApplyPose();StopPose("idle chain first",true);
 idleParent.position={3,4,5};idleParent.rotation=Handshake::XYZ(35,60,10);rotationChild.position={6,7,8};targetHead.position={2,3,4};
 Check(BeginPose(Mode::Custom),"idle-chain restart with different idle pose");pose.clipPaused=true;pose.scrubbing=true;ApplyPose();
 Check(PoseMath::SamePosition(idleParent.position,parentPosition)&&PoseMath::SameRotation(idleParent.rotation,parentRotation)&&PoseMath::SamePosition(rotationChild.position,childPosition),"replay stabilizes rotation-only translation and untracked ancestor pose");
 Check(PoseMath::SamePosition(targetHead.position,{0,.3f,0}),"authored FBX position channel survives idle stabilization");
 StopPose("idle chain restore",true);Check(PoseMath::SamePosition(idleParent.position,{3,4,5})&&PoseMath::SamePosition(rotationChild.position,{6,7,8})&&pins==0&&owners.empty(),"idle-chain stop restores game positions and releases ownership");
 targetRoot.children.pop_back();selectedClip="absolute_test";
 auto calibrationBonesBefore=boneTarget;auto calibrationGripBefore=gripTarget;auto calibrationCurrentBefore=gripCurrent;auto calibrationSlotBefore=selectedSlot;auto calibrationModelBefore=selectedModel;auto calibrationIdentityBefore=selectedIdentity;auto calibrationClipBefore=selectedClip;auto calibrationArmedBefore=armed;auto calibrationKeyBefore=keyDown;auto calibrationModeBefore=armedMode;auto calibrationDraftBefore=workflow.draft;auto calibrationEntry=workflow.draft;calibrationEntry.enabled=true;calibrationEntry.controlled="chr_0003_endminf";calibrationEntry.animation="clip:absolute_test";calibrationEntry.target="chr_0005_chen";workflow.draft=calibrationEntry;Check(PrepareCalibration(calibrationEntry)&&workflow.draft.target=="chr_0004_pelica"&&selectedIdentity=="chr_0004_pelica","calibration automatically selects animation bound squad character");
 targetPresent=false;workflow.draft.target="chr_0005_chen";Check(!PrepareCalibration(calibrationEntry)&&workflow.draft.target=="chr_0005_chen"&&panelStatus.find("佩利卡")!=std::string::npos&&panelStatus.find("加入隊伍")!=std::string::npos,"missing bound character names required member without changing selection");targetPresent=true;armedMode=calibrationModeBefore;workflow.draft=calibrationDraftBefore;boneTarget=calibrationBonesBefore;gripTarget=calibrationGripBefore;gripCurrent=calibrationCurrentBefore;selectedSlot=calibrationSlotBefore;selectedModel=calibrationModelBefore;selectedIdentity=calibrationIdentityBefore;selectedClip=calibrationClipBefore;armed=calibrationArmedBefore;keyDown=calibrationKeyBefore;
 animationLibrary["absolute_test"]->targetCharacter="chr_other";Check(!BeginPose(Mode::Custom)&&pins==0&&owners.empty(),"target-specific FBX clip rejects another character");
 ReferenceMatrix referenceMatrix{};referenceMatrix.m[12]=2;referenceMatrix.m[13]=3;auto matrixData=MatrixJson(referenceMatrix);Check(matrixData[0][3]==2&&matrixData[1][3]==3,"Unity column-major matrix exports explicit JSON rows");Check(QuoteArgument(L"a b\\")==L"\"a b\\\\\"","Blender argument quoting preserves spaces and trailing backslash");
 auto femaleName=go.name;lastControlled="chr_0003_endminf";workflow.draft.controlled="chr_0003_endminf";auto sexOffset=Bones::Defaults();sexOffset[1]=30;boneTarget.Set("0|@root",sexOffset);workflow.ready=true;go.name="chr_0002_endminm_postmodel(Clone)#test";DetectAdministrator();Check(lastControlled=="chr_0002_endminm"&&workflow.draft.controlled==lastControlled&&!workflow.ready&&boneTarget.Get("0|@root")==Bones::Defaults(),"male detection updates draft clears controlled calibration and invalidates prepared state");Check(BeginPose(),"male administrator can bind runtime pose");StopPose("male restore",true);workflow.draft.animation="head";workflow.draft.target="chr_0004_pelica";Check(workflow.Prepare(),"male calibration prepares");Presets::Entry maleEntry;Check(Workflow::Import(Workflow::Export(workflow.prepared),maleEntry)&&maleEntry.controlled=="chr_0002_endminm","male calibration JSON roundtrip keeps identity");Presets::Bank maleBank;Check(workflow.Apply(maleBank,2),"male prepared calibration saves to preset");Presets::Bank maleRead;Check(maleRead.Read(maleBank.Encode())&&maleRead.slots[2].controlled=="chr_0002_endminm","male preset bank roundtrip");auto femaleEntry=maleEntry;femaleEntry.controlled="chr_0003_endminf";Check(!PrepareEntry(femaleEntry)&&PrepareEntry(maleEntry),"wrong sex preset rejected and matching male accepted");go.name=femaleName;DetectAdministrator();Check(workflow.draft.controlled=="chr_0003_endminf"&&!workflow.ready&&maleRead.slots[2].controlled=="chr_0002_endminm","return to female updates draft without rewriting saved male presets");
 ExternalModels::Part hornProfile;hornProfile.id="test-horn";hornProfile.name="角";hornProfile.backend="unity_transform";hornProfile.character="chr_0003_endminf";hornProfile.bone="CustomHorn";externalParts={hornProfile};lastControlled="chr_0003_endminf";
 Object customHorn{"CustomHorn",&root};root.children.push_back(&customHorn);{Pins scanPins;std::vector<Pose::FullBone> scanned;Check(WalkBones(&root,0,scanPins,scanned),"external skeleton scan succeeds");auto horn=std::find_if(scanned.begin(),scanned.end(),[](auto& b){return b.info.name=="CustomHorn";});Check(horn!=scanned.end()&&horn->info.group=="模型骨架","registered external transform outside Bip001 is scanned as model skeleton");}
 root.children.pop_back();externalParts.clear();Check(pins==0&&owners.empty(),"external scan releases pins");
 Check(ConnectionFailure(BE_Result_Conflict,"CameraManager.TailLateTick").find("重啟遊戲")!=std::string::npos,"exclusive camera conflict explains restart recovery");
 Check(ConnectionFailure(BE_Result_NotReady,"runtime").find("尚未就緒")!=std::string::npos,"runtime not ready is distinct from hook conflict");
 auto resetFile=std::filesystem::temp_directory_path()/("bem-mod-reset-"+std::to_string(GetTickCount64())+".ini");{std::ofstream out(resetFile);out<<"[Constants]\nglobal persist $shape = 0.25\n";}auto originalScan=efmiScan;efmiScan.mods={EfmiBridge::Parse(resetFile,EfmiBridge::ReadFile(resetFile),resetFile.parent_path())};efmiScan.mods[0].controls[0].value=.75f;Check(ResetExternalMod(EfmiBridge::Utf8(resetFile))&&efmiScan.mods[0].controls[0].value==.25f&&efmiScan.mods[0].controls[0].dirty,"mod-wide reset restores original INI declared defaults and marks write pending");Check(!ResetExternalMod("missing-file"),"mod-wide reset rejects unknown mod");efmiScan=originalScan;std::filesystem::remove(resetFile);

 // Support settings survive export/import and old settings remain unlocked.
 for(auto mode:Support::Modes){Presets::Entry e;e.enabled=true;e.support=mode;Presets::Entry read;Check(Workflow::Import(Workflow::Export(e),read)&&read.support==mode,"support calibration JSON roundtrip");Workflow::State state;state.draft=e;Presets::Bank slots,loaded;Check(state.Prepare()&&state.Apply(slots,4)&&loaded.Read(slots.Encode())&&loaded.slots[4].support==mode,"support preset save and reload");}
 {Presets::Entry read;auto old=Workflow::Export(Presets::Entry{});old["setting"].erase("support_mode");Check(Workflow::Import(old,read)&&read.support=="none","legacy calibration defaults to no support");old["setting"]["support_mode"]="both_feet";Check(Workflow::Import(old,read)&&read.support=="none","retired both feet setting migrates to no support");old["setting"]["support_mode"]="bad";Check(!Workflow::Import(old,read),"invalid support mode rejected");}
 animationLibrary["absolute_test"]->targetCharacter="chr_0004_pelica";animationLibrary["absolute_test"]->managerAction="none";selectedClip="absolute_test";boneTarget=Bones::Settings{};calibrationMode=true;restoreRequested=false;armed=false;
 Object legsPelvis{"Bip001_Pelvis",&targetRoot,{}, {},{0,1,0}};
 Object leftThigh{"Bip001_L_Thigh",&legsPelvis,{}, {},{-.12f,0,0}},leftCalf{"Bip001_L_Calf",&leftThigh,{}, {},{0,-.45f,.04f}},leftFoot{"Bip001_L_Foot",&leftCalf,{}, {},{0,-.45f,-.04f}};
 Object rightThigh{"Bip001_R_Thigh",&legsPelvis,{}, {},{.12f,0,0}},rightCalf{"Bip001_R_Calf",&rightThigh,{}, {},{0,-.45f,.04f}},rightFoot{"Bip001_R_Foot",&rightCalf,{}, {},{0,-.45f,-.04f}};
 for(auto o:{&legsPelvis,&leftThigh,&leftCalf,&leftFoot,&rightThigh,&rightCalf,&rightFoot})o->hierarchical=true;
 legsPelvis.children={&leftThigh,&rightThigh};leftThigh.children={&leftCalf};leftCalf.children={&leftFoot};rightThigh.children={&rightCalf};rightCalf.children={&rightFoot};targetRoot.children.push_back(&legsPelvis);
 auto supportRootBefore=targetRoot.position;auto supportClip=absolute;supportClip["id"]="support_test";supportClip["actors"][0]["tracks"]=Presets::Json::array();
 for(auto name:{"Bip001_L_Thigh","Bip001_L_Calf","Bip001_R_Thigh","Bip001_R_Calf"}){auto q=Handshake::XYZ(std::string(name).ends_with("Calf")?-45.f:std::string(name).find("_L_")!=std::string::npos?30.f:20.f,0,0);supportClip["actors"][0]["tracks"].push_back({{"bone",name},{"keys",Presets::Json::array({{{"time",0},{"rotation",{q.x,q.y,q.z,q.w}}},{{"time",2},{"rotation",{q.x,q.y,q.z,q.w}}}})}});}
 Check(ImportAnimation(supportClip),"support clip imports");selectedClip="support_test";
 for(auto mode:Support::Modes){supportTarget=mode;leftThigh.rotation=leftCalf.rotation=rightThigh.rotation=rightCalf.rotation={};Check(BeginPose(Mode::Custom),"support mode binds named partner bones");pose.clipPaused=true;pose.scrubbing=true;ApplyPose(0);ApplyBoneLayer();Check(ApplySupport(),"support mode first solve");auto supportFirst=targetRoot.position;
  auto scene=SceneLayout::Build(pose.placement.anchor,pose.placement.anchorRotation,pose.partnerPlacement.anchor,pose.partnerPlacement.anchorRotation,boneTarget.Get("0|@root"),boneTarget.Get("1|@root"));
  for(int tick=0;tick<120&&pose.pins;++tick){Check(RemoveBoneLayer(true),"support layer reverses previous IK before clip evaluation");ApplyPose(0);ApplyBoneLayer();Check(ApplySupport(),"support repeats without accumulation");}
  Check(PoseMath::SamePosition(targetRoot.position,supportFirst),"support root compensation does not accumulate");
  for(int i=0;i<pose.support.count;++i){auto expected=Handshake::Add(scene.partnerPosition,PoseMath::Rotate(scene.partnerRotation,pose.support.legs[i].anchor));Check(Handshake::Length(Handshake::Sub(WorldPosition(static_cast<Object*>(pose.support.legs[i].point)),expected))<.001f,"selected support contact stays fixed within one millimeter");}
  if(std::string(mode)!="none"){auto values=Bones::Defaults();values[3]=15;boneTarget.Set("1|@root",values);Check(RemoveBoneLayer(true),"support restores before root rotation calibration");ApplyPose(0);ApplyBoneLayer();Check(ApplySupport(),"single support handles pivot rotation");auto expected=Handshake::Add(scene.partnerPosition,PoseMath::Rotate(scene.partnerRotation,pose.support.legs[0].anchor));Check(Handshake::Length(Handshake::Sub(WorldPosition(static_cast<Object*>(pose.support.legs[0].point)),expected))<.001f,"root rotation pivots around stationary support point");boneTarget=Bones::Settings{};}
  StopPose("support restore test",true);Check(PoseMath::SamePosition(targetRoot.position,supportRootBefore)&&PoseMath::SameRotation(leftThigh.rotation,{})&&PoseMath::SameRotation(rightCalf.rotation,{})&&pins==0&&owners.empty(),"support stop restores root and pre-animation legs and releases leases");
 }
 calibrationMode=true;supportTarget="left_foot";Check(BeginPose(Mode::Custom),"support starts for timeline and live mode switching");pose.clipPaused=true;pose.scrubbing=true;PumpPose(0);Check(pose.pins&&pose.support.mode=="left_foot","gameplay pipeline applies support after bone offsets");auto lockedFoot=WorldPosition(&leftFoot);pendingSeek=.8f;PumpPose(0);Check(pose.pins&&pose.clipPaused&&std::abs(pose.clipTime-.8f)<.00001f&&Handshake::Length(Handshake::Sub(WorldPosition(&leftFoot),lockedFoot))<.001f,"timeline seek preserves support contact");supportTarget="none";PumpPose(0);Check(pose.pins&&pose.support.mode=="none"&&pose.support.count==0,"switching support off removes prior IK writes");StopPose("support seek restore",true);Check(pins==0&&owners.empty()&&PoseMath::SamePosition(targetRoot.position,supportRootBefore),"support timeline stop restores scene");
 supportTarget="left_foot";leftCalf.children.clear();Check(!BeginPose(Mode::Custom)&&pins==0&&owners.empty(),"missing support bone refuses playback before leases");leftCalf.children={&leftFoot};
 supportTarget="left_foot";Check(BeginPose(Mode::Custom),"support starts for setter failure");pose.clipPaused=true;pose.scrubbing=true;ApplyPose(0);failTargetPlacement=true;Check(!ApplySupport(),"support root setter failure reported");failTargetPlacement=false;StopPose("support partial failure",true);Check(pins==0&&owners.empty()&&PoseMath::SameRotation(leftThigh.rotation,{}),"partial support writes restore and release leases");
 supportTarget="none";targetRoot.children.pop_back();DeleteAnimation("support_test");selectedClip="absolute_test";
 std::erase_if(animationOrder,[](auto& key){return !animationLibrary.contains(key);});
 {BE_ThirdPartyHostV1 supportHost{};supportHost.reply=Reply;host=&supportHost;active=true;workflow.draft.support="none";workflow.ready=true;PanelExecute({InteractionPanel::Action::SupportMode,0,0,"left_knee"});Check(supportTarget=="left_knee"&&workflow.draft.support=="left_knee"&&!workflow.ready&&PanelRead().supportMode=="left_knee","native support selection invalidates prepared settings and updates snapshot");Message("support-web","{\"command\":\"support_set\",\"mode\":\"right_foot\"}");Check(replyResult==BE_Result_Ok&&supportTarget=="right_foot","web support selection updates runtime setting");Message("support-invalid","{\"command\":\"support_set\",\"mode\":\"wrong\"}");Check(replyResult==BE_Result_InvalidArgument&&supportTarget=="right_foot","invalid live support selection does not replace setting");host=nullptr;active=false;supportTarget="none";}

 pendingSelectionStop=false;pendingPreview=false;pendingTimeline=false;pendingSeek.reset();supportTarget="none";boneTarget=Bones::Settings{};workflow.draft.animation="clip:absolute_test";SelectCalibrationAnimation();auto info=TimelineJson();Check(info["duration"]==animationLibrary.at("absolute_test")->duration&&info["paused"]==true&&info["active"]==false&&info["time"]==0,"selection exposes correct paused metadata before playback");Check(TimelineAction(InteractionPanel::Action::Seek,0,.4f)&&std::abs(timelineDraft.time-.4f)<.00001f&&calibrationMode,"timeline action automatically enters calibration and stores seek before live preview");pendingSelectionStop=false;pendingPreview=false;pendingTimeline=false;

 auto previousHook=hook;hook=1;workflow.draft.controlled="chr_0003_endminf";workflow.draft.target="chr_0004_pelica";workflow.draft.enabled=true;workflow.draft.support="none";SelectCalibrationAnimation();PumpCalibrationPreview();Check(SelectedTimelineActive()&&pose.clipPaused&&pose.scrubbing&&pose.clipTime==0,"selection creates live first-frame paused preview on gameplay callback");if(pose.pins){TimelineAction(InteractionPanel::Action::Seek,0,.4f);PumpPose(0);Check(std::abs(pose.clipTime-.4f)<.00001f,"selected preview seeks immediately while paused");SelectCalibrationAnimation();PumpCalibrationPreview();Check(SelectedTimelineActive()&&pose.clipPaused&&pose.clipTime==0,"reselect resets old preview clock to zero");StopPose("selection test restore",true);}hook=previousHook;pendingPreview=false;pendingSelectionStop=false;pendingTimeline=false;
 auto folder=std::filesystem::temp_directory_path()/"interaction-blender-path-test";std::filesystem::create_directories(folder/"Blender 4.5");{std::ofstream exe(folder/"Blender 4.5"/"blender.exe");exe<<"test";}Check(BlenderInFolder(folder)==folder/"Blender 4.5"/"blender.exe","folder picker resolves Blender installation child folder");auto savedBlenderChoice=blenderFolder;blenderFolder=folder.string();Check(BlenderDisplayFolder()==(folder/"Blender 4.5").string(),"panel displays resolved Blender child directory");blenderFolder=savedBlenderChoice;Check(BlenderInFolder(folder/"missing").empty(),"invalid Blender folder is rejected");std::filesystem::remove_all(folder);
 auto importFolder=std::filesystem::temp_directory_path()/"eai-vmd-queue-test";std::filesystem::create_directories(importFolder);
 for(auto name:{"motion.VMD","motion.fbx"}){std::ofstream file(importFolder/name);file<<"queue fixture";}
 auto importHook=hook;hook=1;
 Check(QueueFbxImport((importFolder/"motion.VMD").string())&&fbxJob.mmd,"VMD queues directly with built-in skeleton and case-insensitive format detection");
 Check(!QueueFbxImport((importFolder/"motion.fbx").string())&&fbxJob.mmd,"concurrent import cannot change queued source format");CancelFbxImport();
 Check(QueueFbxImport((importFolder/"motion.fbx").string())&&!fbxJob.mmd,"FBX retains its original converter after VMD cancellation");CancelFbxImport();lastControlled="chr_0003_endminf";Check(QueueFbxImport((importFolder/"motion.VMD").string(),true)&&fbxJob.actor==0&&fbxJob.target==lastControlled&&fbxJob.managerAction=="none","controlled import captures actor and current Endministrator binding");CancelFbxImport();hook=importHook;std::filesystem::remove_all(importFolder);

 // Controlled clips are separate assets; clocks, ranges and restoration must
 // remain independent while both roots share the calibrated scene.
 auto mainJson=absolute;mainJson["id"]="controlled_test";mainJson["name"]="controlled test";mainJson["target_character"]="chr_0003_endminf";mainJson["actors"][0]["role"]="controlled";mainJson["actors"][0]["tracks"][0]["keys"][0]["rotation"]={0,0,0,1};mainJson["actors"][0]["tracks"][0]["keys"][1]["rotation"]={0,.5f,0,.8660254f};
 ImportedAnimation::Clip mainParsed;Check(mainParsed.Read(mainJson)&&mainParsed.targetActor==0,"controlled v2 clip accepts administrator binding");auto badMain=mainJson;badMain["manager_action"]="standing";Check(!mainParsed.Read(badMain),"controlled source rejects overlapping procedural manager layer");
 Check(ImportAnimation(mainJson),"controlled clip imports into library");
 workflow.draft=Presets::Entry{};workflow.draft.enabled=true;workflow.draft.animation="clip:absolute_test";workflow.draft.controlledAnimation="clip:controlled_test";workflow.draft.controlledPose="imported";workflow.draft.controlledSupport="none";controlledSupport="none";supportTarget="none";boneTarget=Bones::Settings{};gripTarget=Grip::Settings{};calibrationLoop=controlledLoop=false;timelineDraft={};mainTimelineDraft={};pendingSelectionStop=false;pendingPreview=false;pendingMainSeek.reset();pendingSeek.reset();hook=1;restoreRequested=false;
 auto mainBefore=head.rotation,partnerBefore=targetHead.rotation;
 SelectCalibrationAnimation(true);PumpCalibrationPreview();Check(pose.pins&&pose.controlledClip&&pose.mainPaused&&pose.clipPaused&&SelectedTimelineActive(true)&&SelectedTimelineActive(),"main selection binds both clips with independent paused clocks");
 TimelineAction(InteractionPanel::Action::Seek,0,.8f,true);PumpPose(0);Check(pose.pins&&std::abs(pose.mainTime-.8f)<.00001f&&pose.clipTime==0,"main seek changes only main clock");
 TimelineAction(InteractionPanel::Action::Seek,0,.3f);PumpPose(0);Check(pose.pins&&std::abs(pose.clipTime-.3f)<.00001f&&std::abs(pose.mainTime-.8f)<.00001f,"partner seek leaves main clock untouched");
 TimelineAction(InteractionPanel::Action::Pause,0,0,true);PumpPose(.03f);Check(pose.pins&&pose.mainTime>.8f&&std::abs(pose.clipTime-.3f)<.00001f,"main resume advances while partner stays paused");
 auto pausedMain=pose.mainTime;TimelineAction(InteractionPanel::Action::Pause,0,0,true);TimelineAction(InteractionPanel::Action::Pause);PumpPose(.03f);Check(pose.pins&&pose.mainTime==pausedMain&&pose.clipTime>.3f,"partner resume advances while main stays paused");
 TimelineAction(InteractionPanel::Action::Seek,0,.2f,true);PumpPose(0);TimelineAction(InteractionPanel::Action::MarkIn,0,0,true);TimelineAction(InteractionPanel::Action::Seek,0,.6f,true);PumpPose(0);TimelineAction(InteractionPanel::Action::MarkOut,0,0,true);TimelineAction(InteractionPanel::Action::RangeLoop,0,0,true);TimelineAction(InteractionPanel::Action::TimelinePlay,0,0,true);for(int i=0;i<40&&pose.pins;++i)PumpPose(.03f);Check(pose.pins&&pose.mainTime>=.2f&&pose.mainTime<.6f&&pose.rangeStart==0&&pose.rangeEnd==2,"main range loop does not modify partner range");
 {BE_ThirdPartyHostV1 mainHost{};mainHost.reply=Reply;host=&mainHost;active=true;auto beforePartnerClock=pose.clipTime;Message("main-timeline","{\"command\":\"timeline_action\",\"actor\":\"controlled\",\"action\":\"seek\",\"time\":0.4}");auto reply=Presets::Json::parse(replyBody);Check(replyResult==BE_Result_Ok&&reply["timeline"]["id"]=="absolute_test"&&reply["controlled_timeline"]["id"]=="controlled_test","main web timeline reply preserves partner/main channel identity");PumpPose(0);Check(std::abs(pose.mainTime-.4f)<.00001f&&pose.clipTime==beforePartnerClock,"main web seek targets main only");PanelExecute({InteractionPanel::Action::MainStep,1});PumpPose(0);Check(std::abs(pose.mainTime-(.4f+1.f/30))<.00001f&&pose.clipTime==beforePartnerClock,"native main frame action routes to main clock");host=nullptr;active=false;}
 auto mainSlice=ImportedAnimation::Slice(*pose.controlledClip,.2f,.6f,"controlled_slice","main slice");ImportedAnimation::Clip mainSliceParsed;Check(mainSliceParsed.Read(mainSlice)&&mainSliceParsed.targetActor==0&&mainSliceParsed.targetCharacter=="chr_0003_endminf","main slice preserves role and target binding");
 auto partnerClock=pose.clipTime;StopAnimationActor(0);PumpPose(.03f);Check(pose.pins&&pose.mainStopped&&!pose.partnerStopped&&pose.clipTime>partnerClock&&PoseMath::SameRotation(head.rotation,mainBefore),"stopping main restores only its overrides while partner continues");
 auto partnerRestartClock=pose.clipTime;QueueCalibrationPreview(false,true);PumpCalibrationPreview();Check(pose.pins&&!pose.mainStopped&&std::abs(pose.clipTime-partnerRestartClock)<.00001f&&!pose.mainPaused,"restarting main preserves partner timeline");
 StopAnimationActor(1);PumpPose(.03f);Check(pose.pins&&pose.partnerStopped&&!pose.mainStopped&&PoseMath::SameRotation(targetHead.rotation,partnerBefore),"stopping partner restores only partner while main continues");StopAnimationActor(0);Check(!pose.pins&&pins==0&&owners.empty(),"stopping both restores scene and releases all resources");
 Check(PrepareCalibration(workflow.draft)&&BeginPose(armedMode),"sync regression begins a fresh dual preview");
 pose.mainStart=pose.rangeStart=0;pose.mainEnd=pose.rangeEnd=2;pose.mainRangeLoop=pose.rangeLoop=false;
 syncAnimations=true;
 TimelineAction(InteractionPanel::Action::Seek,0,.4f,true);PumpPose(0);Check(std::abs(pose.mainTime-.4f)<1e-5f&&std::abs(pose.clipTime-.4f)<1e-5f&&pose.mainPaused&&pose.clipPaused,"synchronized seek targets both clocks and pauses both");
 TimelineAction(InteractionPanel::Action::Step,1,0,false);PumpPose(0);Check(std::abs(pose.mainTime-pose.clipTime)<1e-5f,"partner synchronized step updates main clock");
 TimelineAction(InteractionPanel::Action::MarkIn,0,0,true);Check(std::abs(pose.mainStart-pose.rangeStart)<1e-5f,"synchronized mark-in updates both ranges");
 TimelineAction(InteractionPanel::Action::Seek,0,.8f,false);PumpPose(0);TimelineAction(InteractionPanel::Action::MarkOut,0,0,false);Check(std::abs(pose.mainEnd-pose.rangeEnd)<1e-5f,"synchronized mark-out updates both ranges");
 TimelineAction(InteractionPanel::Action::TimelinePlay,0,0,true);Check(!pose.mainPaused&&!pose.clipPaused,"synchronized play resumes both actors");
 TimelineAction(InteractionPanel::Action::Pause,0,0,false);Check(pose.mainPaused&&pose.clipPaused,"synchronized pause pauses both actors");
 QueueCalibrationStop(true);Check(pendingMainStop&&pendingPartnerStop,"synchronized stop queues both actors");PumpPose(0);Check(!pose.pins,"synchronized stop restores both actors and releases scene");
 {BE_ThirdPartyHostV1 syncHost{};host=&syncHost;active=true;PanelExecute({InteractionPanel::Action::SyncAnimations});active=false;host=nullptr;}Check(!syncAnimations,"shared sync control toggles off");

 auto wrongMainEntry=workflow.draft;auto mainTargetBefore=selectedControlledClip;wrongMainEntry.controlledAnimation="clip:missing";Check(!PrepareEntry(wrongMainEntry)&&selectedControlledClip==mainTargetBefore,"missing main source does not mutate active selection");animationLibrary.at("controlled_test")->targetCharacter="chr_0002_endminm";Check(!PrepareEntry(workflow.draft),"female controller rejects male-bound animation");animationLibrary.at("controlled_test")->targetCharacter="chr_0003_endminf";
 workflow.draft.controlledSupport="left_knee";workflow.draft.support="right_foot";Check(workflow.Prepare(),"dual actor configuration prepares");Presets::Entry dualRoundtrip;Check(Workflow::Import(Workflow::Export(workflow.prepared),dualRoundtrip)&&dualRoundtrip.controlledAnimation=="clip:controlled_test"&&dualRoundtrip.controlledPose=="imported"&&dualRoundtrip.controlledSupport=="left_knee"&&dualRoundtrip.support=="right_foot","dual role animation and supports survive parameter JSON roundtrip");Presets::Bank dualBank;Check(workflow.Apply(dualBank,4),"dual actor configuration saves to shortcut");Presets::Bank dualRead;Check(dualRead.Read(dualBank.Encode())&&dualRead.slots[4].controlledAnimation=="clip:controlled_test","shortcut bank preserves main animation");auto oldBank=dualBank.Encode();for(auto& slot:oldBank["slots"]){slot.erase("controlled_animation");slot.erase("controlled_pose");slot.erase("controlled_support");}Check(dualRead.Read(oldBank)&&dualRead.slots[4].controlledPose=="inherit","previous versions retain imported clip manager presets by default");
 // Main support must use the main lease and actual main skeleton.
 {Object mainFoot{"Bip001_L_Foot"};mainFoot.parent=&root;mainFoot.hierarchical=true;mainFoot.position={.1f,0,0};root.children.push_back(&mainFoot);workflow.draft.support="none";workflow.draft.controlledSupport="left_foot";Check(PrepareCalibration(workflow.draft)&&BeginPose(armedMode)&&pose.mainSupport.mode=="left_foot"&&ApplySupport(0),"controlled support binds actor zero bones and uses its own lease");StopPose("main support restore",true);root.children.pop_back();}
 workflow.draft.controlledSupport="none";workflow.draft.animation="standing";Check(PrepareCalibration(workflow.draft)&&BeginPose(armedMode)&&pose.controlledClip,"controlled-only custom motion starts without a partner imported asset");StopAnimationActor(0);Check(!pose.pins&&pins==0&&owners.empty(),"stopping the sole controlled motion restores the complete preview");
 hook=importHook;selectedControlledClip.clear();controlledPose="inherit";controlledSupport="none";pendingPreview=false;pendingSelectionStop=false;
 return failures?1:0;
}



